main: io.github.thatsmusic99.headsplus.HeadsPlus
name: HeadsPlus
version: ${hp-project.version}
api-version: 1.13
description: Spawns in heads with extra features.
author: Thatsmusic99
contributors: [DariusTK, Toldi, AlansS53, Gniewny, steve4744, Niestrat99, Alexisparis007, jascotty2, Gurbiel, Mistermychciak, Stashenko, Tepoloco, YouHaveTrouble, Bieck_Smile, PaulBGD, andy3559167]
website: 'https://www.spigotmc.org/resources/headsplus-1-8-x-1-15-x.40265/'
# Please note this is mostly to let the weird messages from each plugin work.
# Vault - Economy support
# AdvancedTeleport, AdvancedOreGenerator, SpectateProtection, HeadsPlusCREATION - easter eggs
# PlaceholderAPI - Placeholder support
# WorldGuard, WorldEdit - WG support
softdepend: [Vault, AdvancedTeleport, AdvancedOreGenerator, SpectateProtection, HeadsPlusCREATION, PlaceholderAPI, Ultimate_Economy, WorldGuard, WorldEdit, MythicMobs]
commands:
  head:
    description: Spawns in a head.
    permission: headsplus.head
  headsplus:
    description: Displays the help menu
    aliases: hp
    permission: headsplus.maincommand
  sellhead:
    description: Sells any selected heads in a player's inventory.
    permission: headsplus.sellhead
  heads:
    description: Heads GUI command.
    permission: headsplus.heads
  myhead:
    description: Gets your own head.
    permission: headsplus.myhead
  addhead:
    description: Add a player head to the heads menu.
    permission: headsplus.addhead
  hplb:
    description: Displays the HeadsPlus leaderboards.
    permission: headsplus.leaderboards
  hpc:
    description: Displays available challenges.
    permission: headsplus.challenges

permissions:
  headsplus.*:
    description: Provides access to every single HeadsPlus feature.
    children:
      headsplus.addhead: true
      headsplus.bypass.*: true
      headsplus.craft: true
      headsplus.challenges: true
      headsplus.death.ignore: true
      headsplus.head: true
      headsplus.head.others: true
      headsplus.heads: true
      headsplus.leaderboards: true
      headsplus.maincommand: true
      headsplus.maincommand.*: true
      headsplus.maincommand.complete.others: true
      headsplus.maincommand.debug.*: false
      headsplus.maincommand.headinfo.*: true
      headsplus.maincommand.locale.change: true
      headsplus.maincommand.locale.others: true
      headsplus.maincommand.profile.others: true
      headsplus.maincommand.xp.*: true
      headsplus.myhead: true
      headsplus.notify: true
      headsplus.sellhead: true
      headsplus.sellhead.gui: true
      headsplus.help.viewperms: true
  headsplus.maincommand.*:
    description: Provides access to every subcommand in /hp.
    default: op
    children:
      headsplus.maincommand.complete: true
      headsplus.maincommand.conjure: true
      headsplus.maincommand.debug: true
      headsplus.maincommand.debug.*: false
      headsplus.maincommand.headinfo: true
      headsplus.maincommand.headinfo.*: true
      headsplus.maincommand.info: true
      headsplus.maincommand.locale: true
      headsplus.maincommand.locale.change: true
      headsplus.maincommand.locale.others: true
      headsplus.maincommand.reload: true
      headsplus.maincommand.profile: true
      headsplus.maincommand.profile.others: true
      headsplus.maincommand.tests: true
      headsplus.maincommand.xp: true
      headsplus.maincommand.xp.*: true
  headsplus.maincommand.debug.*:
    description: Provides access to every debug command.
    default: false
    children:
      headsplus.maincommand.debug.dump: true
      headsplus.maincommand.debug.player: true
      headsplus.maincommand.debug.head: true
      headsplus.maincommand.debug.clearim: true
      headsplus.maincommand.debug.item: true
      headsplus.maincommand.debug.delete: true
      headsplus.maincommand.debug.save: true
      headsplus.maincommand.debug.transfer: true
      headsplus.maincommand.debug.fix: true
  headsplus.bypass.*:
    description: Bypasses the majority of HeadsPlus checks.
    default: false
    children:
      headsplus.bypass.blacklist: true
      headsplus.bypass.whitelist: true
      headsplus.bypass.blacklistw: true
      headsplus.bypass.whitelistw: true
      headsplus.bypass.cost: true
      headsplus.bypass.preventplacement: true
  headsplus.maincommand.headinfo.*:
    description: Allows access to some of the /hp headinfo options.
    default: op
    children:
      headsplus.maincommand.headinfo.view: true
      headsplus.maincommand.headinfo.add: true
      headsplus.maincommand.headinfo.remove: true
      headsplus.maincommand.headinfo.set: true
  headsplus.craft:
    default: true
    description: Allows players to craft heads.
  headsplus.challenges:
    default: true
    description: Allows players to use /hpc.
  headsplus.leaderboards:
    default: true
    description: Allows players to use /hplb.
  headsplus.maincommand:
    default: true
    description: Allows players to use /hp or /headsplus.
  headsplus.notify:
    default: op
    description: Notifies players if a new HeadsPlus version is available.
  headsplus.addhead:
    default: op
    description: Allows players to use /addhead.
  headsplus.heads:
    default: true
    description: Allows players to use /heads.
  headsplus.sellhead:
    default: true
    description: Allows players to use /sellhead.
  headsplus.myhead:
    default: true
    description: Allows players to use /myhead.
  headsplus.maincommand.info:
    default: true
    description: Allows players to use /hp info.
  headsplus.maincommand.profile:
    default: true
    description: Allows players to use /hp profile (only to view their own profile).
  headsplus.bypass.cost:
    default: false
    description: Bypass the cost for purchasing all heads
  headsplus.sellhead.gui:
    default: true
    description: Allows you to access the sellhead GUI.
  headsplus.death.ignore:
    default: false
    description: Allows you to not receive a death message when a player drops their head.
  headsplus.head:
    default: true
    description: Allows you to use the /head command.
  headsplus.head.others:
    default: op
    description: Allows you to use the /head command to give heads to other players.
  headsplus.maincommand.complete:
    default: op
    description: Allows you to use the complete subcommand to complete challenges.
  headsplus.maincommand.complete.others:
    default: op
    description: Allows you to fire the complete subcommand and complete challenges for other players.
  headsplus.maincommand.locale.change:
    default: false
    description: Allows you to change the plugin's language for you if the smart locale is enabled.
  headsplus.maincommand.locale.other:
    default: false
    description: Allows you to change other player's plugin language.