name: 🐞 Bug Report
description: Got a bug to report? Here is the template to do so.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - brainsynder-Dev
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">Make sure you are using the latest version of the plugin<br>Snapshot/Dev builds are available on the <a href="https://ci.pluginwiki.us/job/HeadsPlus/">JENKINS</a></div>

- type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: By clicking here you acknowledge that you are using the latest version from the [Jenkins](https://ci.pluginwiki.us/job/SimplePets_v5/)
      options:
        - label: Are you using the latest version/snapshot of HeadsPlus?
          required: true
        - label: Have you checked to see if others have submitted the same bug report?
          required: true
        - label: Have you been able to reproduce the bug more then once?
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Description of the bug
      description: |
        A clear and concise description of what the bug is. [ REQUIRED ]

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: A bug happened!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the bug/issue
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: "Add any other information/notes you'd like to add [ not required ]"
      render: shell
