name: Bug Report
description: Got a bug to report?
title: "[Bug]: "
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: State here when you have checked the following points
      options:
        - label: "Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?"
          required: true
        - label: "Have you checked to see if others have submitted the same bug report?"
          required: true
        - label: "Have you been able to reproduce the bug more then once?"
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Description of the bug
      description: |
        A clear and concise description of what the bug is.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: A bug happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the bug/issue
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: "Add any other information/notes you would like to add."
      render: shell
