name: Feature/Improvement Request
description: Wanting something to be improved about the plugin?
title: "[Feature/Improvement]: "
assignees:
  - Thatsmusic99
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: State here when you have checked the following points
      options:
        - label: "Are you using the latest version/snapshot of HeadsPlus?"
          required: true
        - label: "Have you checked to see if others have submitted the same feature request?"
          required: true

  - type: textarea
    id: request-info
    attributes:
      label: Description of the request
      description: |
        Describe your feature/improvement request here. 
        How do you think it'll help the plugin improve?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: I want this added!
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: "Add any other information/notes you would like to add."
      render: shell
