package io.github.thatsmusic99.headsplus.config.customheads;

public enum HeadsXEnums {

    WOOD_A("wood_a", "&6Wooden A", HeadsPlusConfigCustomHeads.starter + "YTY3ZDgxM2FlN2ZmZTViZTk1MWE0ZjQxZjJhYTYxOWE1ZTM4OTRlODVlYTVkNDk4NmY4NDk0OWM2M2Q3NjcyZSJ9fX0", "alphabet", 0.0),
    WOOD_B("wood_b", "&6Wooden B", HeadsPlusConfigCustomHeads.starter + "NTBjMWI1ODRmMTM5ODdiNDY2MTM5Mjg1YjJmM2YyOGRmNjc4NzEyM2QwYjMyMjgzZDg3OTRlMzM3NGUyMyJ9fX0", "alphabet", 0.0),
    WOOD_C("wood_c", "&6Wooden C", HeadsPlusConfigCustomHeads.starter + "YWJlOTgzZWM0NzgwMjRlYzZmZDA0NmZjZGZhNDg0MjY3NjkzOTU1MWI0NzM1MDQ0N2M3N2MxM2FmMThlNmYifX19", "alphabet", 0.0),
    WOOD_D("wood_d", "&6Wooden D", HeadsPlusConfigCustomHeads.starter + "MzE5M2RjMGQ0YzVlODBmZjlhOGEwNWQyZmNmZTI2OTUzOWNiMzkyNzE5MGJhYzE5ZGEyZmNlNjFkNzEifX19", "alphabet", 0.0),
    WOOD_E("wood_e", "&6Wooden E", HeadsPlusConfigCustomHeads.starter + "ZGJiMjczN2VjYmY5MTBlZmUzYjI2N2RiN2Q0YjMyN2YzNjBhYmM3MzJjNzdiZDBlNGVmZjFkNTEwY2RlZiJ9fX0", "alphabet", 0.0),
    WOOD_F("wood_f", "&6Wooden F", HeadsPlusConfigCustomHeads.starter + "YjE4M2JhYjUwYTMyMjQwMjQ4ODZmMjUyNTFkMjRiNmRiOTNkNzNjMjQzMjU1OWZmNDllNDU5YjRjZDZhIn19fQ", "alphabet", 0.0),
    WOOD_G("wood_g", "&6Wooden G", HeadsPlusConfigCustomHeads.starter + "MWNhM2YzMjRiZWVlZmI2YTBlMmM1YjNjNDZhYmM5MWNhOTFjMTRlYmE0MTlmYTQ3NjhhYzMwMjNkYmI0YjIifX19", "alphabet", 0.0),
    WOOD_H("wood_h", "&6Wooden H", HeadsPlusConfigCustomHeads.starter + "MzFmMzQ2MmE0NzM1NDlmMTQ2OWY4OTdmODRhOGQ0MTE5YmM3MWQ0YTVkODUyZTg1YzI2YjU4OGE1YzBjNzJmIn19fQ", "alphabet", 0.0),
    WOOD_I("wood_i", "&6Wooden I", HeadsPlusConfigCustomHeads.starter + "NDYxNzhhZDUxZmQ1MmIxOWQwYTM4ODg3MTBiZDkyMDY4ZTkzMzI1MmFhYzZiMTNjNzZlN2U2ZWE1ZDMyMjYifX19", "alphabet", 0.0),
    WOOD_J("wood_j", "&6Wooden J", HeadsPlusConfigCustomHeads.starter + "M2E3OWRiOTkyMzg2N2U2OWMxZGJmMTcxNTFlNmY0YWQ5MmNlNjgxYmNlZGQzOTc3ZWViYmM0NGMyMDZmNDkifX19", "alphabet", 0.0),
    WOOD_K("wood_k", "&6Wooden K", HeadsPlusConfigCustomHeads.starter + "OTQ2MWIzOGM4ZTQ1NzgyYWRhNTlkMTYxMzJhNDIyMmMxOTM3NzhlN2Q3MGM0NTQyYzk1MzYzNzZmMzdiZTQyIn19fQ", "alphabet", 0.0),
    WOOD_L("wood_l", "&6Wooden L", HeadsPlusConfigCustomHeads.starter + "MzE5ZjUwYjQzMmQ4NjhhZTM1OGUxNmY2MmVjMjZmMzU0MzdhZWI5NDkyYmNlMTM1NmM5YWE2YmIxOWEzODYifX19", "alphabet", 0.0),
    WOOD_M("wood_m", "&6Wooden M", HeadsPlusConfigCustomHeads.starter + "NDljNDVhMjRhYWFiZjQ5ZTIxN2MxNTQ4MzIwNDg0OGE3MzU4MmFiYTdmYWUxMGVlMmM1N2JkYjc2NDgyZiJ9fX0", "alphabet", 0.0),
    WOOD_N("wood_n", "&6Wooden N", HeadsPlusConfigCustomHeads.starter + "MzViOGIzZDhjNzdkZmI4ZmJkMjQ5NWM4NDJlYWM5NGZmZmE2ZjU5M2JmMTVhMjU3NGQ4NTRkZmYzOTI4In19fQ", "alphabet", 0.0),
    WOOD_O("wood_o", "&6Wooden O", HeadsPlusConfigCustomHeads.starter + "ZDExZGUxY2FkYjJhZGU2MTE0OWU1ZGVkMWJkODg1ZWRmMGRmNjI1OTI1NWIzM2I1ODdhOTZmOTgzYjJhMSJ9fX0", "alphabet", 0.0),
    WOOD_P("wood_p", "&6Wooden P", HeadsPlusConfigCustomHeads.starter + "YTBhNzk4OWI1ZDZlNjIxYTEyMWVlZGFlNmY0NzZkMzUxOTNjOTdjMWE3Y2I4ZWNkNDM2MjJhNDg1ZGMyZTkxMiJ9fX0", "alphabet", 0.0),
    WOOD_Q("wood_q", "&6Wooden Q", HeadsPlusConfigCustomHeads.starter + "NDM2MDlmMWZhZjgxZWQ0OWM1ODk0YWMxNGM5NGJhNTI5ODlmZGE0ZTFkMmE1MmZkOTQ1YTU1ZWQ3MTllZDQifX19", "alphabet", 0.0),
    WOOD_R("wood_r", "&6Wooden R", HeadsPlusConfigCustomHeads.starter + "YTVjZWQ5OTMxYWNlMjNhZmMzNTEzNzEzNzliZjA1YzYzNWFkMTg2OTQzYmMxMzY0NzRlNGU1MTU2YzRjMzcifX19", "alphabet", 0.0),
    WOOD_S("wood_s", "&6Wooden S", HeadsPlusConfigCustomHeads.starter + "M2U0MWM2MDU3MmM1MzNlOTNjYTQyMTIyODkyOWU1NGQ2Yzg1NjUyOTQ1OTI0OWMyNWMzMmJhMzNhMWIxNTE3In19fQ", "alphabet", 0.0),
    WOOD_T("wood_t", "&6Wooden T", HeadsPlusConfigCustomHeads.starter + "MTU2MmU4YzFkNjZiMjFlNDU5YmU5YTI0ZTVjMDI3YTM0ZDI2OWJkY2U0ZmJlZTJmNzY3OGQyZDNlZTQ3MTgifX19", "alphabet", 0.0),
    WOOD_U("wood_u", "&6Wooden U", HeadsPlusConfigCustomHeads.starter + "NjA3ZmJjMzM5ZmYyNDFhYzNkNjYxOWJjYjY4MjUzZGZjM2M5ODc4MmJhZjNmMWY0ZWZkYjk1NGY5YzI2In19fQ", "alphabet", 0.0),
    WOOD_V("wood_v", "&6Wooden V", HeadsPlusConfigCustomHeads.starter + "Y2M5YTEzODYzOGZlZGI1MzRkNzk5Mjg4NzZiYWJhMjYxYzdhNjRiYTc5YzQyNGRjYmFmY2M5YmFjNzAxMGI4In19fQ", "alphabet", 0.0),
    WOOD_W("wood_w", "&6Wooden W", HeadsPlusConfigCustomHeads.starter + "MjY5YWQxYTg4ZWQyYjA3NGUxMzAzYTEyOWY5NGU0YjcxMGNmM2U1YjRkOTk1MTYzNTY3ZjY4NzE5YzNkOTc5MiJ9fX0", "alphabet", 0.0),
    WOOD_X("wood_x", "&6Wooden X", HeadsPlusConfigCustomHeads.starter + "NWE2Nzg3YmEzMjU2NGU3YzJmM2EwY2U2NDQ5OGVjYmIyM2I4OTg0NWU1YTY2YjVjZWM3NzM2ZjcyOWVkMzcifX19", "alphabet", 0.0),
    WOOD_Y("wood_y", "&6Wooden Y", HeadsPlusConfigCustomHeads.starter + "YzUyZmIzODhlMzMyMTJhMjQ3OGI1ZTE1YTk2ZjI3YWNhNmM2MmFjNzE5ZTFlNWY4N2ExY2YwZGU3YjE1ZTkxOCJ9fX0", "alphabet", 0.0),
    WOOD_Z("wood_z", "&6Wooden Z", HeadsPlusConfigCustomHeads.starter + "OTA1ODJiOWI1ZDk3OTc0YjExNDYxZDYzZWNlZDg1ZjQzOGEzZWVmNWRjMzI3OWY5YzQ3ZTFlMzhlYTU0YWU4ZCJ9fX0", "alphabet", 0.0),
    WOOD_ASCII_A("wood_ascii_a", "&6Wooden Ascii A", HeadsPlusConfigCustomHeads.starter + "MTVjZDZkYjllYzNjN2Q5MTEzZTZkZDQ5YTE2Zjk5YTMyNmI5ZjU5NGNlOTg3ZjkxOTU1OWFjN2RiZDNiNTU1In19fQ", "alphabet", 0.0),
    WOOD_ASCII_O("wood_ascii_o", "&6Wooden Ascii O", HeadsPlusConfigCustomHeads.starter + "NmVkYmI0NGM2MzliOTUzMDhmZmNkZjhjNDc3MGRmZThiMDJkNzUyZGVjNGIzMTk2ZjRhOGY5YWMyMzE1MzkzYSJ9fX0", "alphabet", 0.0),
    WOOD_ASCII_U("wood_ascii_u", "&6Wooden Ascii U", HeadsPlusConfigCustomHeads.starter + "N2I1MmI5NGM2NTE2Y2JlNDYxZmVhNjIxZDMxNmNlZTBiODc1ZjBmYmMyMzlkMjUyNzNlODI0YjYxM2U3M2RkNCJ9fX0", "alphabet", 0.0),
    WOOD_1("wood_1", "&6Wooden 1", HeadsPlusConfigCustomHeads.starter + "NzFiYzJiY2ZiMmJkMzc1OWU2YjFlODZmYzdhNzk1ODVlMTEyN2RkMzU3ZmMyMDI4OTNmOWRlMjQxYmM5ZTUzMCJ9fX0", "alphabet", 0.0),
    WOOD_2("wood_2", "&6Wooden 2", HeadsPlusConfigCustomHeads.starter + "NGNkOWVlZWU4ODM0Njg4ODFkODM4NDhhNDZiZjMwMTI0ODVjMjNmNzU3NTNiOGZiZTg0ODczNDE0MTk4NDcifX19", "alphabet", 0.0),
    WOOD_3("wood_3", "&6Wooden 3", HeadsPlusConfigCustomHeads.starter + "MWQ0ZWFlMTM5MzM4NjBhNmRmNWU4ZTk1NTY5M2I5NWE4YzNiMTVjMzZiOGI1ODc1MzJhYzA5OTZiYzM3ZTUifX19", "alphabet", 0.0),
    WOOD_4("wood_4", "&6Wooden 4", HeadsPlusConfigCustomHeads.starter + "ZDJlNzhmYjIyNDI0MjMyZGMyN2I4MWZiY2I0N2ZkMjRjMWFjZjc2MDk4NzUzZjJkOWMyODU5ODI4N2RiNSJ9fX0", "alphabet", 0.0),
    WOOD_5("wood_5", "&6Wooden 5", HeadsPlusConfigCustomHeads.starter + "NmQ1N2UzYmM4OGE2NTczMGUzMWExNGUzZjQxZTAzOGE1ZWNmMDg5MWE2YzI0MzY0M2I4ZTU0NzZhZTIifX19", "alphabet", 0.0),
    WOOD_6("wood_6", "&6Wooden 6", HeadsPlusConfigCustomHeads.starter + "MzM0YjM2ZGU3ZDY3OWI4YmJjNzI1NDk5YWRhZWYyNGRjNTE4ZjVhZTIzZTcxNjk4MWUxZGNjNmIyNzIwYWIifX19", "alphabet", 0.0),
    WOOD_7("wood_7", "&6Wooden 7", HeadsPlusConfigCustomHeads.starter + "NmRiNmViMjVkMWZhYWJlMzBjZjQ0NGRjNjMzYjU4MzI0NzVlMzgwOTZiN2UyNDAyYTNlYzQ3NmRkN2I5In19fQ", "alphabet", 0.0),
    WOOD_8("wood_8", "&6Wooden 8", HeadsPlusConfigCustomHeads.starter + "NTkxOTQ5NzNhM2YxN2JkYTk5NzhlZDYyNzMzODM5OTcyMjI3NzRiNDU0Mzg2YzgzMTljMDRmMWY0Zjc0YzJiNSJ9fX0", "alphabet", 0.0),
    WOOD_9("wood_9", "&6Wooden 9", HeadsPlusConfigCustomHeads.starter + "ZTY3Y2FmNzU5MWIzOGUxMjVhODAxN2Q1OGNmYzY0MzNiZmFmODRjZDQ5OWQ3OTRmNDFkMTBiZmYyZTViODQwIn19fQ", "alphabet", 0.0),
    WOOD_0("wood_0", "&6Wooden 0", HeadsPlusConfigCustomHeads.starter + "MGViZTdlNTIxNTE2OWE2OTlhY2M2Y2VmYTdiNzNmZGIxMDhkYjg3YmI2ZGFlMjg0OWZiZTI0NzE0YjI3In19fQ", "alphabet", 0.0),
    WOOD_SPACE("wood_space", "&6Wooden Space", HeadsPlusConfigCustomHeads.starter + "NWRiNTMyYjVjY2VkNDZiNGI1MzVlY2UxNmVjZWQ3YmJjNWNhYzU1NTk0ZDYxZThiOGY4ZWFjNDI5OWM5ZmMifX19", "alphabet", 0.0),
    WOOD_COLON("wood_colon", "&6Wooden Colon", HeadsPlusConfigCustomHeads.starter + "Y2NiZWUyOGUyYzc5ZGIxMzhmMzk3N2JhNDcyZGZhZTZiMTFhOWJiODJkNWIzZDdmMjU0NzkzMzhmZmYxZmU5MiJ9fX0", "alphabet", 0.0),
    WOOD_SLASH("wood_slash", "&6Wooden Slash", HeadsPlusConfigCustomHeads.starter + "N2Y5NWQ3YzFiYmYzYWZhMjg1ZDhkOTY3NTdiYjU1NzIyNTlhM2FlODU0ZjUzODlkYzUzMjA3Njk5ZDk0ZmQ4In19fQ", "alphabet", 0.0),
    PORTABLE_GRILL("portable_grill", "&7Portable Grill", HeadsPlusConfigCustomHeads.starter + "MzE4ZTM1ZWM0YjRiNGMxNTkxYzUxNzczODZkZTE4Nzk3NDU0Mjk4Yjc0NTU5ODJlM2FlODNiYWNjZWQwZjFhMiJ9fX0", "decoration", 0.0),
    BEER_BARREL("beer_barrel", "&6Beer Barrel&7]", HeadsPlusConfigCustomHeads.starter + "ZmZiOTg1OTYyZjQ2ZTA1NWY1M2Q4ZWUzNWIxMWI4YTYyZjM5N2RhZDlkYjlmZWFlZmY0ODI5NjMwZDlkOSJ9fX0", "decoration", 0.0),
    PRESENT("present", "&cPresent 1", HeadsPlusConfigCustomHeads.starter + "YmQ3YTlmNmVkMDhkZDIxN2ZkZjA5ZjQ2NTJiZjZiN2FmNjIxZTFkNWY4OTYzNjA1MzQ5ZGE3Mzk5OGE0NDMifX19", "decoration", 0.0),
    PRESENT_1("present_1", "&9Present 2", HeadsPlusConfigCustomHeads.starter + "ZjU2MTJkYzdiODZkNzFhZmMxMTk3MzAxYzE1ZmQ5NzllOWYzOWU3YjFmNDFkOGYxZWJkZjgxMTU1NzZlMmUifX19", "decoration", 0.0),
    PARCEL("parcel", "&6Parcel", HeadsPlusConfigCustomHeads.starter + "MTYyMzRhZTdkNTU5MDNlYThiYzM0NDEzY2Q1MmRlZDNiMzdjOTJlZWU1YWU1MzNmYzUxMjZhNjU0NjFmMTFmIn19fQ", "decoration", 0.0),
    LAVA_BUCKET("lava_bucket", "&6Lava Bucket", HeadsPlusConfigCustomHeads.starter + "OGQ1NDI3YTgzNTQwYTA4YTNmYTJlNjU1YzI5NjRhMDcyNDM1MTQ1ODRhNzFlYzM1ZDZiOWUxODRkZmJlMzE4In19fQ", "decoration", 0.0),
    WATER_BUCKET("water_bucket", "&3Water Bucket", HeadsPlusConfigCustomHeads.starter + "NDlmMWYwN2UyYjFjMzJiYjY0YTEyOGU1MjlmM2FmMWU1Mjg2ZTUxODU0NGVkZjhjYmFhNmM0MDY1YjQ3NmIifX19", "decoration", 0.0),
    BUCKET("bucket", "&7Bucket", HeadsPlusConfigCustomHeads.starter + "MjFlYTgyNTE1MGIwNmU2NWUyY2ViNTkzYWZlMzQyZGNhNTZkZGExMmJmNmM5Njk2ZmI4MmY5MGRjZDQyM2FiIn19fQ", "decoration", 0.0),
    CCTV("cctv", "&7CCTV", HeadsPlusConfigCustomHeads.starter + "ZWIyOGY0ZWVmZjg5MWI3OGQ1MWY3NWQ4NzIyYzYyODQ4NGJhNDlkZjljOWYyMzcxODk4YzI2OTY3Mzg2In19fQ", "decoration", 0.0),
    RADIO("radio", "&7Radio", HeadsPlusConfigCustomHeads.starter + "MTQ4YThjNTU4OTFkZWM3Njc2NDQ0OWY1N2JhNjc3YmUzZWU4OGEwNjkyMWNhOTNiNmNjN2M5NjExYTdhZiJ9fX0", "decoration", 0.0),
    BLACK_DICE("black_dice", "&7Black Dice", HeadsPlusConfigCustomHeads.starter + "OTE1ZjdjMzEzYmNhOWMyZjk1OGU2OGFiMTRhYjM5Mzg2N2Q2NzUwM2FmZmZmOGYyMGNiMTNmYmU5MTdmZDMxIn19fQ", "decoration", 0.0),
    WHITE_DICE("white_dice", "&fWhite Dice", HeadsPlusConfigCustomHeads.starter + "Nzk3OTU1NDYyZTRlNTc2NjY0NDk5YWM0YTFjNTcyZjYxNDNmMTlhZDJkNjE5NDc3NjE5OGY4ZDEzNmZkYjIifX19", "decoration", 0.0),
    RED_DICE("red_dice", "&cRed Dice", HeadsPlusConfigCustomHeads.starter + "NTEzMWRlOGU5NTFmZGQ3YjlhM2QyMzlkN2NjM2FhM2U4NjU1YTMzNmI5OTliOWVkYmI0ZmIzMjljYmQ4NyJ9fX0", "decoration", 0.0),
    GLOBE("globe", "&bGlobe", HeadsPlusConfigCustomHeads.starter + "YjFkZDRmZTRhNDI5YWJkNjY1ZGZkYjNlMjEzMjFkNmVmYTZhNmI1ZTdiOTU2ZGI5YzVkNTljOWVmYWIyNSJ9fX0", "decoration", 0.0),
    TOASTER("toaster", "&7Toaster", HeadsPlusConfigCustomHeads.starter + "MzExNmY4OWQyZThkYmQxMjY2MzY0MTVmOTMyODY0MWM2ZmEyODkwYzMyZDQzOWVmZmMzOGEyMjk2YzJkIn19fQ", "decoration", 0.0),
    TNT("tnt", "&cTNT", HeadsPlusConfigCustomHeads.starter + "M2FmNTk3NzZmMmYwMzQxMmM3YjU5NDdhNjNhMGNmMjgzZDUxZmU2NWFjNmRmN2YyZjg4MmUwODM0NDU2NWU5In19fQ", "decoration", 0.0),
    PEARL("pearl", "&fPearl", HeadsPlusConfigCustomHeads.starter + "N2QxNmFlOTUxMTIwMzk0ZjM2OGYyMjUwYjdjM2FkM2ZiMTJjZWE1NWVjMWIyZGI1YTk0ZDFmYjdmZDRiNmZhIn19fQ", "decoration", 0.0),
    CHIMNEY("chimney", "&7Chimney", HeadsPlusConfigCustomHeads.starter + "ZTQ1MmQ3ZThiOWE4ZmUzZGY5MTU1ODQyMjI4NDZjZjk4ODU0ODc1OGI0ODU1NmFiNGM4NjgzZDA4NGNhNWZjOSJ9fX0", "decoration", 0.0),
    RED_CANDLE("red_candle", "&cRed Candle", HeadsPlusConfigCustomHeads.starter + "OWZkZGRkYjhlZWUxMWJjMzEyZDFhY2ZkNjIxYTQ0NmI1Njg2OGFhZjY2YTUwNzFjYTk0MjU1ODJiMThjZGQ2In19fQ", "decoration", 0.0),
    WHITE_CANDLE("white_candle", "&fWhite Candle", HeadsPlusConfigCustomHeads.starter + "NzgxMjI2NjU2ZDgyNTI5MWIxZDdlNDU2Yjc0ZWNkY2UyODY3MjE2OTY0MWU2YzM1YjFlMjNiOWI0MDI3NGUifX19", "decoration", 0.0),
    MONITOR("monitor", "&7Monitor", HeadsPlusConfigCustomHeads.starter + "MzMzZGNmYjRkYTEwMTc3MjY0OTY4YjQ0OWU3MjRhZGViZWUzYmMzM2I3MmJhZTg1ODQyYjRhYWI5YmQ5YzRkYiJ9fX0", "decoration", 0.0),
    COOKING_POT("cooking_pot", "&7Cooking Pot&7]", HeadsPlusConfigCustomHeads.starter + "MmIxNDZlMWNmMWFhYzQwZDM3OTFjODk4MWEzMjhkNTVmOTc0YThiOWY3YjNhYmRlM2Q0YjkxODczNGVhNyJ9fX0", "decoration", 0.0),
    LANTERN("lantern", "&6Lantern", HeadsPlusConfigCustomHeads.starter + "MTk5OGUzNjY4YTZjYTYyZWI3NWYzNmZhNGJiN2Y1ZWNkYjI2YjE3MGFhY2QzMzc3ZGI1M2Y2MmYxODhiMzgifX19", "decoration", 0.0),
    PAPER_LANTERN("paper_lantern", "&cPaper Lantern", HeadsPlusConfigCustomHeads.starter + "MjYyODNlN2E4OGQzMjcxOTMwNGEzN2VkZTBjNmE4YzVkYzlkOWNmOWIwMGExNzljZjkwNGU4Y2U4MjEzMTIifX19", "decoration", 0.0),
    SNOW_GLOBE("snow_globe", "&bSnow Globe", HeadsPlusConfigCustomHeads.starter + "NmRkNjYzMTM2Y2FmYTExODA2ZmRiY2E2YjU5NmFmZDg1MTY2YjRlYzAyMTQyYzhkNWFjODk0MWQ4OWFiNyJ9fX0", "decoration", 0.0),
    SPEAKER("speaker", "&7Speaker", HeadsPlusConfigCustomHeads.starter + "NTM1OTZmZDdiZTZiNzQ2M2U3ZDJjYzQ1ODQ0NWU2YTBhOWExODNkOGY0Y2ZjYzgwMTE4YmE3MTNhN2RkMTgifX19", "decoration", 0.0),
    ROSE_POT("rose_pot", "&cRose Pot", HeadsPlusConfigCustomHeads.starter + "OWRiYTM4ZTlmYzY3ZjcyYzQ1OGZkYWM4ZWNkN2NhYmFlZDNlYjgzNzM3MTQzYTAxMjgzNTBhMWFiMzgxZTNlIn19fQ", "decoration", 0.0),
    SALVIA_POT("salvia_pot", "&9Salvia Pot", HeadsPlusConfigCustomHeads.starter + "ZWQ4MGMyNmY5MDRiNTdlNjMxZTM5ZWJjNDQ2ZWMxYWYyZGNlMzQzMmViODQzMWZiZDE5MDg3YWRiNGFiY2IifX19", "decoration", 0.0),
    TOILET_PAPER("toilet_paper", "&fToilet Paper", HeadsPlusConfigCustomHeads.starter + "NzM4MGM3ZTYyMWExZjRkYTU0M2U0YzdhYjE0OTRlZTE4NGI4N2JiMTMyNDE4NTEyYzllZWU4NThmOWRlMWRiIn19fQ", "decoration", 0.0),
    FISHBOWL("fishbowl", "&bFishbowl", HeadsPlusConfigCustomHeads.starter + "ZWYxMmUwZGZlNjhhZWY3Y2I1YzA2Yzc3Y2YyNzIyMzBhNWNkNjgyYmM0NTJjYjY5OWIyMTc3ZGY1ZTZhZjY0In19fQ", "decoration", 0.0),
    BEACH_BALL("beach_ball", "&eBeach Ball", HeadsPlusConfigCustomHeads.starter + "NWE1YWIwNWVhMjU0YzMyZTNjNDhmM2ZkY2Y5ZmQ5ZDc3ZDNjYmEwNGU2YjVlYzJlNjhiM2NiZGNmYWMzZmQifX19", "decoration", 0.0),
    SOCCER_BALL("soccer_ball", "&fSoccer Ball", HeadsPlusConfigCustomHeads.starter + "OGU0YTcwYjdiYmNkN2E4YzMyMmQ1MjI1MjA0OTFhMjdlYTZiODNkNjBlY2Y5NjFkMmI0ZWZiYmY5ZjYwNWQifX19", "decoration", 0.0),
    FIRE_CHARGE("fire_charge", "&cFire Charge", HeadsPlusConfigCustomHeads.starter + "OWMyZTlkODM5NWNhY2Q5OTIyODY5YzE1MzczY2Y3Y2IxNmRhMGE1Y2U1ZjNjNjMyYjE5Y2ViMzkyOWM5YTExIn19fQ", "decoration", 0.0),
    BASKETBALL("basketball", "&6Basketball", HeadsPlusConfigCustomHeads.starter + "ZWRmODQ3MTVhNjRkYzQ1NTg2ZjdhNjA3OWY4ZTQ5YTk0NzdjMGZlOTY1ODliNGNmZDcxY2JhMzIyNTRhYzgifX19", "decoration", 0.0),
    CANNONBALL("cannonball", "&7Cannonball", HeadsPlusConfigCustomHeads.starter + "OTk2NzU0ZDMzMDQzNTM0NWFhZTNhOWYwNjNjZmNhNDJhZmIyOGI3YzVjNGJiOWYyOTRlZDI1MjdkOTYxIn19fQ", "decoration", 0.0),
    CLOCK("clock", "&6Clock", HeadsPlusConfigCustomHeads.starter + "ODQ3N2RhZmM4YzllYTA3OTk2MzMzODE3OTM4NjZkMTQ2YzlhMzlmYWQ0YzY2ODRlNzExN2Q5N2U5YjZjMyJ9fX0", "decoration", 0.0),
    RUBIKS_CUBE("rubiks_cube", "&cRubik's Cube", HeadsPlusConfigCustomHeads.starter + "OGYxYTI3N2JlYjllNGZhYTZlN2UzNTZjNzQ3ODZlOTY2MTU1NzM2YTY4NThiZjViYjVhZDI5ZGY1YmFiNjFhMSJ9fX0", "decoration", 0.0),
    LETTER_BOX("letter_box", "&9Letter Box", HeadsPlusConfigCustomHeads.starter + "ZWIyODE1Yjk5YzEzYmZjNTViNGM1YzI5NTlkMTU3YTYyMzNhYjA2MTg2NDU5MjMzYmMxZTRkNGY3ODc5MmM2OSJ9fX0", "decoration", 0.0),
    BASKET("basket", "&6Basket", HeadsPlusConfigCustomHeads.starter + "MzEzODVhN2FmYjM1NTJmYWY3MWMyYzVhOGU2YTViMWQyZTY3MmM3ODZlODA3NDQzM2ViNTgzOWFjZTgzYjQifX19", "decoration", 0.0),
    PAPERS("papers", "&fPapers", HeadsPlusConfigCustomHeads.starter + "YzY2OTJmOTljYzZkNzgyNDIzMDQxMTA1NTM1ODk0ODQyOThiMmU0YTAyMzNiNzY3NTNmODg4ZTIwN2VmNSJ9fX0", "decoration", 0.0),
    RED_LANTERN("red_lantern", "&cRed Lantern", HeadsPlusConfigCustomHeads.starter + "ZTFiOGZkYTQzMTFmNzQ3M2JjOTQ4ZmI1NWExNzI0YzUzYWZmYTZmYmEzM2U3NWQ0MTM2ZWYwM2ZhOThhOGMifX19", "decoration", 0.0),
    YELLOW_LANTERN("yellow_lantern", "&eYellow Lantern", HeadsPlusConfigCustomHeads.starter + "M2QyNWU0NjcxOWY5NjdiMzNjMjk3ZWQxNGE1MWJlOTRlZDY0YmJlZDM2MmFhYzkxYzc5ZjM5MDNlMWVhNDkxIn19fQ", "decoration", 0.0),
    OFF_LANTERN("off_lantern", "&7Off Lantern", HeadsPlusConfigCustomHeads.starter + "MzczYTExNTI4MzAyZjI1NDJkMTk2N2JmYzY3ZGFiM2FmNWQ1ZjFmNzZjMzYwZWI2N2I3MWIyYWU0YzNmN2IifX19", "decoration", 0.0),
    SNOWMAN_HEAD("snowman_head", "&fSnowman Head", HeadsPlusConfigCustomHeads.starter + "OThlMzM0ZTRiZWUwNDI2NDc1OWE3NjZiYzE5NTVjZmFmM2Y1NjIwMTQyOGZhZmVjOGQ0YmYxYmIzNmFlNiJ9fX0", "decoration", 0.0),
    FAN("fan", "&7Fan", HeadsPlusConfigCustomHeads.starter + "MTcyNzcxZmMxMTczNzA2M2M4MWViNzU5NzNlOWI4MjU5MDk1MWUzNjc0ZjMxYWNjZThjZGRkMWFhZDFiIn19fQ", "decoration", 0.0),
    CHESS_BOARD("chess_board", "&fChess Board", HeadsPlusConfigCustomHeads.starter + "OTQwOTRlZmZlZTRiYTJhYjFjMmZjNmM4ZWQxYzQ2OTBmYmExOWM4NjYxN2U5MjI3ZGIxZjU4ZDhkZDVkIn19fQ", "decoration", 0.0),
    PROJECTOR("projector", "&7Projector", HeadsPlusConfigCustomHeads.starter + "MjhmMjI0ZDZiNmM4NmU2YjIxZWQ0MGMwMWFkZTNjYTFlMGExNWNiOTdkZWZhZDc4YThkMThlZjRhNTUxYjZhMiJ9fX0", "decoration", 0.0),
    TISSUE_BOX("tissue_box", "&bTissue Box", HeadsPlusConfigCustomHeads.starter + "ZTZiOGJiOWM0NmNmNzlkZjIxNDdkMjNmMjhmZGRlYmU4ZTNiYWM3NjU4MGYzZDZkZDU1ZDhlOTFhZTdiMCJ9fX0", "decoration", 0.0),
    MICROWAVE("microwave", "&7Microwave", HeadsPlusConfigCustomHeads.starter + "ZmNkNDdjNzQ3NDczM2NmYzRmZGRhZTY5ZTQxNTQxM2U1OGFkMzllMjUxNDI0ZjZlMWFlNjdjZmNmNTVjNjgyIn19fQ", "decoration", 0.0),
    WOODEN_CRATE("wooden_crate", "&6Wooden Crate", HeadsPlusConfigCustomHeads.starter + "YWYyMmI2YTNhMGYyNGJkZWVhYjJhNmFjZDliMWY1MmJiOTU5NGQ1ZjZiMWUyYzA1ZGRkYjIxOTQxMGM4In19fQ", "decoration", 0.0),
    FIRE("fire", "&cFire", HeadsPlusConfigCustomHeads.starter + "NDA4MGJiZWZjYTg3ZGMwZjM2NTM2YjY1MDg0MjVjZmM0Yjk1YmE2ZThmNWU2YTQ2ZmY5ZTljYjQ4OGE5ZWQifX19", "decoration", 0.0),
    WII_CONSOLE("wii_console", "&fWii Console", HeadsPlusConfigCustomHeads.starter + "YjYzYTM5NTljMjU5NjcxZjJkYjMzZTU1NDIyY2I5ZDM2NmZiYjRhMjQyOTFlNWZlZTVlYzUzZmRiMTVmNDNmZSJ9fX0", "decoration", 0.0),
    PLAYSTATION("playstation", "&7Playstation", HeadsPlusConfigCustomHeads.starter + "Njg1ZTQ0ZDBlYTZkZTdiNGQ0OTY5NWE0Y2U5OTJhYzkwYjVlZjI3YmM4NWQ5NDFlNmZlODkwY2JmNmE5OCJ9fX0", "decoration", 0.0),
    XBOX("xbox", "&7XBox", HeadsPlusConfigCustomHeads.starter + "Y2Q0OWI0NGVjMDk0N2MyMjMxZThmODc5ZWJhYTg5ZDU1MjkzYTg3MjE5YTYxYjZhNWNmZGRkODgzYmI3NyJ9fX0", "decoration", 0.0),
    FLOWER_POT("flower_pot", "&7Flowerpot", HeadsPlusConfigCustomHeads.starter + "MWIyZjZmYWYxYjk5YWMzOGQ1MmIxYzdiYzQ5ZWI3OTFjNjcwNTQzMzdkNDRkODNkNjZhZGVjYjUwZjM3NSJ9fX0", "decoration", 0.0),
    BREAD("bread", "&6Bread", HeadsPlusConfigCustomHeads.starter + "NTE5OTdkYTY0MDQzYjI4NDgyMjExNTY0M2E2NTRmZGM0ZThhNzIyNjY2NGI0OGE0ZTFkYmI1NTdiNWMwZmUxNCJ9fX0", "food_and_drink", 0.0),
    CHEESE("cheese", "&eCheese", HeadsPlusConfigCustomHeads.starter + "MzZjMDFiZmZlY2ZkYWI2ZDNjMGYxYTdjNmRmNmFhMTkzNmYyYWE3YTUxYjU0YTRkMzIzZTFjYWNiYzUzOSJ9fX0", "food_and_drink", 0.0),
    CHOCOLATE_DONUT("chocolate_donut", "&6Chocolate Donut", HeadsPlusConfigCustomHeads.starter + "NTlkYTU0ZmYzNjZlNzM4ZTMxZGU5MjkxOTk4NmFiYjRkNTBjYTk0NGZhOTkyNmFmNjM3NThiNzQ0OGYxOCJ9fX0", "food_and_drink", 0.0),
    WHITE_DONUT("white_donut", "&fWhite donut", HeadsPlusConfigCustomHeads.starter + "ZDA3YjhjNTFhY2VjMmE1MDhiYjJmYTY1MmZiNmU0YTA4YjE5NDg1MTU5YTA5OWY1OTgyY2NiODhkZjFmZTI3ZSJ9fX0", "food_and_drink", 0.0),
    PINK_DONUT("pink_donut", "&dPink Donut", HeadsPlusConfigCustomHeads.starter + "ZDA3YjhjNTFhY2VjMmE1MDhiYjJmYTY1MmZiNmU0YTA4YjE5NDg1MTU5YTA5OWY1OTgyY2NiODhkZjFmZTI3ZSJ9fX0", "food_and_drink", 0.0),
    TACO("taco", "&6Taco", HeadsPlusConfigCustomHeads.starter + "MWFkN2MwYTA0ZjE0ODVjN2EzZWYyNjFhNDhlZTgzYjJmMWFhNzAxYWIxMWYzZmM5MTFlMDM2NmE5Yjk3ZSJ9fX0", "food_and_drink", 0.0),
    POPCORN("popcorn", "&ePopcorn", HeadsPlusConfigCustomHeads.starter + "MTQ5N2IxNDdjZmFlNTIyMDU1OTdmNzJlM2M0ZWY1MjUxMmU5Njc3MDIwZTRiNGZhNzUxMmMzYzZhY2RkOGMxIn19fQ", "food_and_drink", 0.0),
    PANCAKES("pancakes", "&6Pancakes", HeadsPlusConfigCustomHeads.starter + "YmJhYTdmOGU0MzcxMTJiM2I2NTY5NDcxNTk2ZDViNjFkYWE3YTNiNDA4MzkxZDFlZDQzMmY1MzE3Nzk2YTIifX19", "food_and_drink", 0.0),
    BOWL_OF_RICE("bowl_of_rice", "&9Bowl of Rice", HeadsPlusConfigCustomHeads.starter + "NGE5MWYyNWI3ZTEwNTcxOGY5Zjk3OTljNjIxZjNiZWJkM2FhZWZjMThjMjAxOTA2MjMzOGE1MTExMjhjNDU2In19fQ", "food_and_drink", 0.0),
    SALMON("salmon", "&cSalmon", HeadsPlusConfigCustomHeads.starter + "YjE3ZWRhMWY2NWJkYzhlZDQxYWFhNGNjYWE0ZTJiZWQ2OTQ3MTRlMzI4NjdlZTE2YWYzMWY0YzQyZWYxZjI4In19fQ", "food_and_drink", 0.0),
    SUNDAE("sundae", "&eSundae", HeadsPlusConfigCustomHeads.starter + "OTUzNjZjYTE3OTc0ODkyZTRmZDRjN2I5YjE4ZmViMTFmMDViYTJlYzQ3YWE1MDM1YzgxYTk1MzNiMjgifX19", "food_and_drink", 0.0),
    PEPSI("pepsi", "&9Pe&fp&csi", HeadsPlusConfigCustomHeads.starter + "MmJiYWU2ZGY5OWRjODJiZWFmNDlkMDY0ZGY3NGExYmJjMTVlOGUzNzY1MzMyNzY5MTJjOGM4ZmU1OWNiNGY0In19fQ", "food_and_drink", 0.0),
    FANTA("fanta", "&6Fanta", HeadsPlusConfigCustomHeads.starter + "MmJlOTUwNWEzOGExNGQxNTEyYzc4OTJmYzQ0ZDNkN2NlNjMzOGIxYmYwZjkxMjM3MjFiMTIxYTE0YjA5NWEzIn19fQ", "food_and_drink", 0.0),
    COCA_COLA("coca_cola", "&cCoca &fCola", HeadsPlusConfigCustomHeads.starter + "OTNiMDFmYjJmNmJhNDdjOWQ3NjM4NDkxZjM3Y2Q4NTgyYTkzNzczMTE4NmRmNGQxZWNjZDU5YjY1YmYzNyJ9fX0", "food_and_drink", 0.0),
    WATER("water", "&9Water", HeadsPlusConfigCustomHeads.starter + "YWVkOGE5ODVkYTdiMzRiZjkyODdiYWQyMWY2YmZlY2FiMWQ5MGZiOGEyZjlmMTMwNWJmMzI4ZWE4ZGNmIn19fQ", "food_and_drink", 0.0),
    RED_WINE("red_wine", "&cRed Wine", HeadsPlusConfigCustomHeads.starter + "Yjc1NTg0ZTZmZDU0Y2EwMWRmNGVmZmQ1Zjc0NmIyZDgzYTU4OWRlNjc3NzU1NzU2YmI1OGQ5ZWEyODQ1MTYifX19", "food_and_drink", 0.0),
    SANDWICH("sandwich", "&6Sandwich", HeadsPlusConfigCustomHeads.starter + "OTQ5NjU4OWZiNWMxZjY5Mzg3YjdmYjE3ZDkyMzEyMDU4ZmY2ZThlYmViM2ViODllNGY3M2U3ODE5NjExM2IifX19", "food_and_drink", 0.0),
    BEER("beer", "&eBeer", HeadsPlusConfigCustomHeads.starter + "NDA1M2UyNjg2N2JiNTc1MzhlOTc4OTEzN2RiYmI1Mzc3NGUxOGVkYTZmZWY1MWNiMmVkZjQyNmIzNzI2NCJ9fX0", "food_and_drink", 0.0),
    RED_JAM("red_jam", "&cRed Jam", HeadsPlusConfigCustomHeads.starter + "YzBiOGI1ODg5ZWUxYzYzODhkYzZjMmM1ZGJkNzBiNjk4NGFlZmU1NDMxOWEwOTVlNjRkYjc2MzgwOTdiODIxIn19fQ", "food_and_drink", 0.0),
    NUTELLA("nutella", "&7N&cutella", HeadsPlusConfigCustomHeads.starter + "NTE1ZGNiMmRhMDJjZjczNDgyOWUxZTI3M2UzMDI1NjE3ZDgwNzE1MTZmOTUzMjUxYjUyNTQ1ZGE4ZDNlOGRiOCJ9fX0", "food_and_drink", 0.0),
    FRIES("fries", "&6Fries", HeadsPlusConfigCustomHeads.starter + "YTBlYWNhYzQxYTllYWYwNTEzNzZlZjJmOTU5NzAxZTFiYmUxYmY0YWE2NzE1YWRjMzRiNmRjMjlhMTNlYTkifX19", "food_and_drink", 0.0),
    BURGER("burger", "&6Burger", HeadsPlusConfigCustomHeads.starter + "YTZlZjFjMjVmNTE2ZjJlN2Q2Zjc2Njc0MjBlMzNhZGNmM2NkZjkzOGNiMzdmOWE0MWE4YjM1ODY5ZjU2OWIifX19", "food_and_drink", 0.0),
    CANDY_BOWL("candy_bowl", "&aCandy Bowl", HeadsPlusConfigCustomHeads.starter + "YzY4ZjFjMzM2MjViNGI0NGMzNjdiNTRjNTRhYmQxY2VhMDg4MzQ1MWYxN2Q0ZjcwM2JhM2E4N2JiOWI4MDM3In19fQ", "food_and_drink", 0.0),
    BUTTER("butter", "&eButter", HeadsPlusConfigCustomHeads.starter + "YjY2YjE5ZjdkNjM1ZDAzNDczODkxZGYzMzAxN2M1NDkzNjMyMDlhOGY2MzI4YTg1NDJjMjEzZDA4NTI1ZSJ9fX0", "food_and_drink", 0.0),
    SPAGHETTI("spaghetti", "&6Spaghetti", HeadsPlusConfigCustomHeads.starter + "M2M0NmJlYzVhMjVlM2RlNmQxZTY1MWM3NWI1ZWU4YzQxZDQ2NmIyMjdkM2ZhMjdkMWYyODk5NTRjMTQ5NyJ9fX0", "food_and_drink", 0.0),
    HOT_DOG("hot_dog", "&cHot Dog", HeadsPlusConfigCustomHeads.starter + "MWNhNDVmZDc1NWYyYjMyMGY2OWYxMjYwZmEzM2JkYTkzNGM5ZDJkMzE1ZTkxZmFkYWU3ZGM1ZjlmM2FmNTAifX19", "food_and_drink", 0.0),
    OWL("owl", "&7Owl", HeadsPlusConfigCustomHeads.starter + "NjY0Njk0YjY4MTY1YmI5YWFiZTc5ZTEzYmM4ODdlODhmZjNiMGRmYmYzNGNjYWFjYzJhM2FkNGE5ZGRmOWUyIn19fQ", "animals", 0.0),
    ROBIN("robin", "&6Robin", HeadsPlusConfigCustomHeads.starter + "Yjk2MjczNzBmZWRiZDBiYWU3YmFlNmQ2Zjg1ODM1NTU3NjM3ODljMWJkOTNmYTYzOWNmYTNkZmQ0OGUzNDg1MCJ9fX0", "animals", 0.0),
    BLUE_BIRD("blue_bird", "&3Blue Bird", HeadsPlusConfigCustomHeads.starter + "NjRkNTMzMzNmMThjY2Q3YTdmYWU1OWY4NDE1YTQzOGVjOWI2NTM1OTk4OTYyNjk1Y2M0ZjY4ZWQyZDMxIn19fQ", "animals", 0.0),
    BLUE_BIRD2("blue_bird2", "&1Blue Bird", HeadsPlusConfigCustomHeads.starter + "YjZkY2MwNjhmNjIwNmY5YjRjMmMzZDNjNjRjMDk1N2FjYjUxYjExZmNlNTEyYTZmNDk4NDgzNjg2OWYwIn19fQ", "animals", 0.0),
    WHITE_BIRD("white_bird", "&fWhite Bird", HeadsPlusConfigCustomHeads.starter + "YzNiZGU0MzExMWY2OWE3ZmRhNmVjNmZhZjIyNjNjODI3OTYxZjM5MGQ3YzYxNjNlZDEyMzEwMzVkMWIwYjkifX19", "animals", 0.0),
    PARROT("parrot", "&cPa&frr&1ot", HeadsPlusConfigCustomHeads.starter + "YzEzNWY1ODM4ZTUxNTg1ZTE1OTQyZThmMmYxY2MzNmRhOTYzMDcwZGRkNWJhMzVhZjk1ZWQzN2ViNmMzIn19fQ", "animals", 0.0),
    CHICKEN("chicken", "&fChicken", HeadsPlusConfigCustomHeads.starter + "N2YzN2Q1MjRjM2VlZDE3MWNlMTQ5ODg3ZWExZGVlNGVkMzk5OTA0NzI3ZDUyMTg2NTY4OGVjZTNiYWM3NWUifX19", "animals", 0.0),
    PANDA("panda", "&fPanda", HeadsPlusConfigCustomHeads.starter + "ZDhjZGQ0ZjI4NTYzMmMyNWQ3NjJlY2UyNWY0MTkzYjk2NmMyNjQxYjE1ZDliZGJjMGExMTMwMjNkZTc2YWIifX19", "animals", 0.0),
    TURTLE("turtle", "&aTurtle", HeadsPlusConfigCustomHeads.starter + "MTJlNTQ4NDA4YWI3NWQ3ZGY4ZTZkNWQyNDQ2ZDkwYjZlYzYyYWE0ZjdmZWI3OTMwZDFlZTcxZWVmZGRmNjE4OSJ9fX0", "animals", 0.0),
    BEE("bee", "&6Bee", HeadsPlusConfigCustomHeads.starter + "OTQ3MzIyZjgzMWUzYzE2OGNmYmQzZTI4ZmU5MjUxNDRiMjYxZTc5ZWIzOWM3NzEzNDlmYWM1NWE4MTI2NDczIn19fQ", "animals", 0.0),
    DOGE("doge", "&6Doge", HeadsPlusConfigCustomHeads.starter + "ZThlNmY3Nzk1ZGYyZWI4ZDdmNGZmNWQwYWVkNTI5YmU4MTEzNGQ5N2JiNTEyNjNlMzhjYjY5NGQ2NzA0ZGE0In19fQ", "animals", 0.0),
    LIZARD("lizard", "&aLizard", HeadsPlusConfigCustomHeads.starter + "OWRhMjgxM2Q0ZjVhY2Q2OWVkNTkwYzFkOGE0NDJiNTk1NTE5ZGNiYzBlMTcxOThhZGZhYWFhZjE1Zjg5YjAifX19", "animals", 0.0),
    ELEPHANT("elephant", "&7Elephant", HeadsPlusConfigCustomHeads.starter + "NzcxZTgyOTY1ZDMzMjEzZWYyNmY2Yjg5NzIyZWRlZTQzNDZjMzU0YzA4ZTM0ZWNmY2ZkNmRkZDM2MWE5ZTdlIn19fQ", "animals", 0.0),
    RACOON("racoon", "&7Racoon", HeadsPlusConfigCustomHeads.starter + "OGE5YTk2YTI2Yjc4YzViODM3NGY1ODBkZmZmYzgxOTlhYTE3NjcxYjRjNTMyZGRkNTQ1MjE3YmIyNTE3NmVkIn19fQ", "animals", 0.0),
    LLAMA("llama", "&6Llama", HeadsPlusConfigCustomHeads.starter + "ODE4Y2Q0NTdmYmFmMzI3ZmEzOWYxMGI1YjM2MTY2ZmQwMTgyNjQwMzY4NjUxNjRjMDJkOWU1ZmY1M2Y0NSJ9fX0", "animals", 0.0),
    POLAR_BEAR("polar_bear", "&fPolar Bear", HeadsPlusConfigCustomHeads.starter + "NDQyMTIzYWMxNWVmZmExYmE0NjQ2MjQ3Mjg3MWI4OGYxYjA5YzFkYjQ2NzYyMTM3NmUyZjcxNjU2ZDNmYmMifX19", "animals", 0.0),
    YOUTUBE("youtube", "&cYouTube", HeadsPlusConfigCustomHeads.starter + "ZDJmNmMwN2EzMjZkZWY5ODRlNzJmNzcyZWQ2NDU0NDlmNWVjOTZjNmNhMjU2NDk5YjVkMmI4NGE4ZGNlIn19fQ", "logos", 0.5),
    FACEBOOK("facebook", "&9Facebook", HeadsPlusConfigCustomHeads.starter + "ZGViNDYxMjY5MDQ0NjNmMDdlY2ZjOTcyYWFhMzczNzNhMjIzNTliNWJhMjcxODIxYjY4OWNkNTM2N2Y3NTc2MiJ9fX0", "logos", 0.5),
    SKYPE("skype", "&bSkype", HeadsPlusConfigCustomHeads.starter + "MmVjMTgyZGE3ZDNjMGE4YWNjM2JlOWI3N2MyOWJlNDdlMDhjMjBiMDUwYjEzZmQ0YzRjN2Q3MWY2NjI3MyJ9fX0", "logos", 0.5),
    INSTAGRAM("instagram", "&fInstagram", HeadsPlusConfigCustomHeads.starter + "YWM4OGQ2MTYzZmFiZTdjNWU2MjQ1MGViMzdhMDc0ZTJlMmM4ODYxMWM5OTg1MzZkYmQ4NDI5ZmFhMDgxOTQ1MyJ9fX0", "logos", 0.5),
    REDDIT("reddit", "&fReddit!", HeadsPlusConfigCustomHeads.starter + "NGQ5YmQ0YjJmYThkYTgyNDdhODJjM2QxZmEyNDY3MTVmOWI2ZDk4Yzc3ODM3NGRhNmVmYzEwYzg5Y2Q2NCJ9fX0", "logos", 0.5),
    TWITCH("twitch", "&5Twitch", HeadsPlusConfigCustomHeads.starter + "NDZiZTY1ZjQ0Y2QyMTAxNGM4Y2RkZDAxNThiZjc1MjI3YWRjYjFmZDE3OWY0YzFhY2QxNThjODg4NzFhMTNmIn19fQ", "logos", 0.5),
    GOOGLE_CHROME("google_chrome", "&cGoogle &aChrome", HeadsPlusConfigCustomHeads.starter + "NTY5MzZkNGYwZDFiOTNmZWY3NzViMWZiZDE5MjgxYjcwYzZmODg0NzViYjVhNDFiZjM3MmMxMmYxZjhhMjIifX19", "logos", 0.5),
    TWITTER("twitter", "&bTwitter", HeadsPlusConfigCustomHeads.starter + "MzY4NWEwYmU3NDNlOTA2N2RlOTVjZDhjNmQxYmEyMWFiMjFkMzczNzFiM2Q1OTcyMTFiYjc1ZTQzMjc5In19fQ", "logos", 0.5),
    DISCORD("discord", "&9Discord", HeadsPlusConfigCustomHeads.starter + "Nzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19", "logos", 0.5),
    SNAPCHAT("snapchat", "&eSnapchat", HeadsPlusConfigCustomHeads.starter + "ODczNTgyOWFkMGE4NzhmOTYwZDc5NGE2MWUzZjE3MjVmZmQxYTBkNTRmNzRjZDk0NjUyY2I2OWIyNGUzIn19fQ", "logos", 0.5),
    IMGUR("imgur", "&aImgur", HeadsPlusConfigCustomHeads.starter + "MWY1ODc3MjJlNjdhZjRhZjg4Y2ZhZWM2NmViZjFjY2U2YzdmYmM1MzZiNWMyNTY1MmFmNjM3NzcyMDQ3OTAifX19", "logos", 0.5),
    MOJANG("mojang", "&cMojang", HeadsPlusConfigCustomHeads.starter + "Zjc3MDVlM2U5OTdlNWNlNTIxNjY2M2M5ZTY0YjM5NmZhNDNlZGRlODI1NWZkOTEwZjBjYzgxYTAzMjVlNmIifX19", "logos", 0.5),
    PATREON("patreon", "&cPatreon", HeadsPlusConfigCustomHeads.starter + "NTY5M2I2NmE1OTVmNzhhZjNmNTFmNGVmYTRjMTMzNzViMWI5NThlNmY0YzUwN2E0N2M0ZmU1NjVjYzI3NSJ9fX0", "logos", 0.5),
    PINTEREST("pinterest", "&cPinterest", HeadsPlusConfigCustomHeads.starter + "ZThlNzY2N2E3M2EwMDc0ZmUxYWVhNzRkMWI2YjNiYTNjZTQ5ZjE4MTkyYjRmN2Q1ZDhmZTYzNmUwYzU0ZiJ9fX0", "logos", 0.5),
    DEVIANTART("deviantart", "&aDeviantArt", HeadsPlusConfigCustomHeads.starter + "Y2VhNGRiZTkzZDhkM2JhNzE3NzkxNDM2ZWVjYWE1YjdlMmU4NDJmNGIxNjFmZWYxYzZmMWQ2NTkyIn19fQ", "logos", 0.5),
    MIXER("mixer", "&3Mixer", HeadsPlusConfigCustomHeads.starter + "OGM3MmJiZDM2ZDIyMTdmYTg2ZjI2ODJlNjdkNjRhYWJhYzYxNWIyZTIwNTQxZmY0ZDcxODk5ZDQwNmViIn19fQ", "logos", 0.5),
    IOS_APPLE("ios_apple", "&fApple", HeadsPlusConfigCustomHeads.starter + "OGNmODExZmExMDljZGU2MjljNzEyY2NkM2ZjOTI4OWU2NzhhNWUxODg5NGY0ODhjMDc0NDQ4ZTQ4ZDg1MiJ9fX0", "logos", 0.5),
    SPOTIFY("spotify", "&aSpotify", HeadsPlusConfigCustomHeads.starter + "ZmU3OTJkMzhlNDE2OGQyNmRlNzc4Mzk4NGNhZmZmYzYwYjQ4ODM4ZDgxZjIyOTYwNzZmZTE0ZGVkZDYifX19", "logos", 0.5),
    PAYPAL("paypal", "&9Pay&3Pal", HeadsPlusConfigCustomHeads.starter + "ZDRkY2ZjZmFmNzcwZTU2M2MwY2ZkY2QzMDZhMTg1ZWE5NDIzZmUxNjljY2FjZWE2YjkwMzdmMjMzYTJiZjVjIn19fQ", "logos", 0.5),
    NETFLIX("netflix", "&cNetflix", HeadsPlusConfigCustomHeads.starter + "NDYzYWQ4Y2JmNjhhODQyYzM0MWM5Y2NjMzQzM2I0NDNmMDNmNzdiMGRlMjY0OGJjYzkzYzRjNDdhODA2ZCJ9fX0", "logos", 0.5),
    GITHUB("github", "&fGitHub", HeadsPlusConfigCustomHeads.starter + "MjZlMjdkYTEyODE5YThiMDUzZGEwY2MyYjYyZGVjNGNkYTkxZGU2ZWVlYzIxY2NmM2JmZTZkZDhkNDQzNmE3In19fQ", "logos", 0.5),
    WOOD_HEART("wood_heart", "&6Wooden Heart", HeadsPlusConfigCustomHeads.starter + "MzM2ZmViZWNhN2M0ODhhNjY3MWRjMDcxNjU1ZGRlMmExYjY1YzNjY2IyMGI2ZThlYWY5YmZiMDhlNjRiODAifX19", "alphabet", 0.5),
    WOOD_MINUS("wood_minus", "&6Wooden Minus", HeadsPlusConfigCustomHeads.starter + "YmQ4YTk5ZGIyYzM3ZWM3MWQ3MTk5Y2Q1MjYzOTk4MWE3NTEzY2U5Y2NhOTYyNmEzOTM2Zjk2NWIxMzExOTMifX19", "alphabet", 0.5),
    WOOD_HASHTAG("wood_hashtag", "&6Wooden Hashtag", HeadsPlusConfigCustomHeads.starter + "OWFlODVmNzRmOGUyYzA1NGI3ODFhMjlmYTliMjU5MzRiYTYzYmI3OWYxZGU4YTk1YjQzNmQ5YmZkY2FmNGNkIn19fQ", "alphabet", 0.5),
    WOOD_UNDERSCORE("wood_underscore", "&6Wooden Underscore", HeadsPlusConfigCustomHeads.starter + "Nzk2NmY4OTFjMTU0NmFlY2JmY2MzYmFlZGNmYjY3MDc5ZDdmMmE2YThiNzM5ZWQ1YmFjMmJiM2NmMzA4ZDM4In19fQ", "alphabet", 0.5),
    WOOD_SQUARE_BRACKET_1("wood_square_bracket", "&6Wooden Square Bracket", HeadsPlusConfigCustomHeads.starter + "MmNjNmJkMTNhNjFmY2JhNGEzODU5ZWMwNmJiOGM4MjM3MzliNmJlYWNiYThjZmEwMTUyZThjNjBkYjk0In19fQ", "alphabet", 0.5),
    WOOD_SQUARE_BRACKET_2("wood_square_bracket_2", "&6Wooden Square Bracket", HeadsPlusConfigCustomHeads.starter + "YTY1MDczMzZlMzUwNjZkYWE4ZTRlNmU2MjRmOTNmNjVlMzVlZTk3NGU5ZThiNjRkMmRkOTkwNGVjZWZkYTIifX19", "alphabet", 0.5),
    WOOD_PERCENTAGE("wood_percentage", "&6Wooden Percentage", HeadsPlusConfigCustomHeads.starter + "NTA4NTFjZjA2MjU0OGM0MzYyNTNjMzM3YTQxMTJjZmM5ODU0NDNhNzQ4ZDkzMWNmMjAxZDFlODRmYzcyYjEyYyJ9fX0", "alphabet", 0.5),
    WOOD_QUOTES("wood_quotes", "&6Wooden Quotation Mark", HeadsPlusConfigCustomHeads.starter + "NDc1N2U5NzJjNzYzMTQ5NDc2YmM1NTZjZmJhZDM2MTRjMWQ0OTk1NGYxM2Y4ODkzZWI5ZDEwNTg0NTc1M2YyZSJ9fX0", "alphabet", 0.5),
    WOOD_SEMI_COLON("wood_semi_colon", "&6Wooden Semi Colon", HeadsPlusConfigCustomHeads.starter + "OTcxZjRkMmJmZmI1OTRjMTU4YzZjZTFlZjlkOTgyYjZmZDI0NTgyNzVlN2Y4OTY1NWJiNzRlZGU3NjhkZWQifX19", "alphabet", 0.5),
    WOOD_COMMA("wood_comma", "&6Wooden Comma", HeadsPlusConfigCustomHeads.starter + "Nzg0MGI0ZTdhNjgwNDM0ODU3NDI3MTExYmRhZjY0ZTdmYmE5MTJlYTU3MDcxODJlOThiYzU4NWNjYjUzIn19fQ", "alphabet", 0.5),
    WOOD_CURLY_BRACKET("wood_curly_bracket", "&6Wooden Curly Bracket", HeadsPlusConfigCustomHeads.starter + "NjE3NmVmMDU1ODgxNWI3ZjA1YzE1M2NmNGNkYzY5ZjliYTRiYTFjMTBlYTFhODc0OWFlYjhjMmI5NzdlIn19fQ", "alphabet", 0.5),
    WOOD_CURLY_BRACKET_2("wood_curly_bracket_2", "&6Wooden Curly Bracket", HeadsPlusConfigCustomHeads.starter + "ODNiMTNmZjhlN2EzZmFiNWZmMWU5OGU4ZmQ5MzljYzA5N2I2YjQ1Yzg1MjQwZDMyNDUwOTk0Zjc2NzE0MzlkIn19fQ", "alphabet", 0.5),
    WOOD_EQUALS_SIGN("wood_equals_sign", "&6Wooden Equals Sign", HeadsPlusConfigCustomHeads.starter + "Nzg3Njg5ZjgzMzQzNmFhNzExYWJiZDQ1MTY4ODU2Nzc1YTJiMTE0NjU2Y2RmNGRjNWE2YzZmMWFmYWU1MjAifX19", "alphabet", 0.5),
    WOOD_PLUS_SIGN("wood_plus_sign", "&6Wooden Plus Sign", HeadsPlusConfigCustomHeads.starter + "M2VkZDIwYmU5MzUyMDk0OWU2Y2U3ODlkYzRmNDNlZmFlYjI4YzcxN2VlNmJmY2JiZTAyNzgwMTQyZjcxNiJ9fX0", "alphabet", 0.5),
    RAINBOW_SUNDAE("rainbow_sundae", "&cR&ea&ai&bn&3b&5o&dw &cS&eu&an&bd&5a&de", HeadsPlusConfigCustomHeads.starter + "Njk2YTgxYjk5NDQ0ZGQ1M2FhYTAxOTdmMzdiZTdiMDM4MzgzYWU4NWNjM2E2MzhiZTU0ZTdiNzZkZjM2YTJjIn19fQ", "food_and_drink", 0.8),
    MONOCHROME_SUNDAE("monochrome_sundae", "&7Monochrome &fSundae", HeadsPlusConfigCustomHeads.starter + "NGJlYTYyNmQyN2ZkYmQ2Y2I5OTI3MmViZTBiZjE1OWU5MjRkNWMwYTMxNzNmZDVjMmI1MTI4Y2RhZGY3MzcifX19", "food_and_drink", 0.8),
    MELON_SUNDAE("melon_sundae", "&cMelon &aSundae", HeadsPlusConfigCustomHeads.starter + "MTE4YjQ0NzE2M2M2NzhhYmI5NTZhMzkyODg3OGYzZjJkNWJiMTU3NzJiMTM4ZmRhYmI3MTJjNTliYjhhZDM1In19fQ", "food_and_drink", 0.8),
    LEMON_SUNDAE("lemon_sundae", "&eLemon Sundae", HeadsPlusConfigCustomHeads.starter + "ZGUyNjExNTE4MDM3NTM2NmJiMzRlZDE2YzI2Y2UyZDA0ZDkxZjdmNTI3Mjc2YWMyNDcwZTllYmFmMmRhZjM1In19fQ", "food_and_drink", 0.8),
    STRAWBERRY_SUNDAE("strawberry_sundae", "&cStrawberry Sundae", HeadsPlusConfigCustomHeads.starter + "YzU5ZjRiNGYxYThiZjRmNGFkNjg3NGY5MzBhYzdkN2U5M2U5OTA2MWY4NzlhYjgwNDI4ZjUyZTc1N2EyOSJ9fX0", "food_and_drink", 0.8),
    BANANASPLIT_SUNDAE("bananasplit_sundae", "&eBanana Split Sundae", HeadsPlusConfigCustomHeads.starter + "Y2FkMmU2NDYzOGRhZmRlYjI0Yzk1NjU4YjZhYmFiMjM2ZDIzZWI5MzQxZTk4YTI0MzdiYTYxMTk0OTQ4OWEifX19", "food_and_drink", 0.8),
    ROSEBUSH("rosebush", "&cRose &aBush", HeadsPlusConfigCustomHeads.starter + "ODJmNzNhZTAyZGJkYmNhNzhmZmZmNTIzNTA5NWVlN2Y4NzZlYWE1YTNjOGNkNWJlZDI1N2M0YWNjNTZmMTM2OCJ9fX0", "plants", 1.0),
    WHITE_FLOWER_BUSH("white_flower_bush", "&aBush", HeadsPlusConfigCustomHeads.starter + "YWM4NzQ0YzJkMmZlOTU3ZjgwNzg0NzZlZDgwOWJhZmQ4YTU0NmVhNzE4ZDEwNDRhMDk5YTgxNGEyNzM2OTUwIn19fQ", "plants", 1.0),
    BLUEBERRY_BUSH("blueberry_bush", "&9Blueberry &aBush", HeadsPlusConfigCustomHeads.starter + "ZWE4YjY3NDc5ZjEyMmJkNjA1ZWUwYzA5ODVhZWNkN2JiODEwOTA5NWE4ZGZmOGU1ZjdlYzk2NDhlMTE4In19fQ", "plants", 1.0),
    WHITE_BERRY_BUSH("white_berry_bush", "&aBush", HeadsPlusConfigCustomHeads.starter + "Njg5NGRhYmU1OGI1ZTQ0YzA4NTFkMjYzMWZmNmQ3OWI1Yjg3NmE0YTEyYmIxY2MyNmQyODc3Mzk5ZmU2MTIyIn19fQ", "plants", 1.0),
    RED_FLOWER_BUSH("red_flower_bush", "&aBush", HeadsPlusConfigCustomHeads.starter + "ODVjZTQwZWVmODY5YmUyY2Y4ODg4OWRhOTI2OGNmZGU2ZDkzMTliMzc3ODU4OWFkNDdlOWQzNWFhYThmMWQifX19", "plants", 1.0),
    YELLOW_FLOWER_BUSH("yellow_flower_bush", "&aBush", HeadsPlusConfigCustomHeads.starter + "MzUzZWYxYTU0MjY5ODNhMWQxMTczN2Y3YTQyODZmYTcxOGI4M2Q1NGUyMzcxNzlmYzhiOGU4NGM2ODIifX19", "plants", 1.0),
    RED_FLOWER_BUSH_2("red_flower_bush_2", "&aBush", HeadsPlusConfigCustomHeads.starter + "NDBhYjVmN2I3NWI2NjIzNzg3NjgxMWVjOTRjMjcyMjgzOWY3MGRiMWRjYzY3ZGUzN2Q3NjdmMmU5NDFiZiJ9fX0", "plants", 1.0),
    PINK_FLOWER_BUSH("pink_flower_bush", "&aBush", HeadsPlusConfigCustomHeads.starter + "NDBhYjVmN2I3NWI2NjIzNzg3NjgxMWVjOTRjMjcyMjgzOWY3MGRiMWRjYzY3ZGUzN2Q3NjdmMmU5NDFiZiJ9fX0", "plants", 1.0),
    RED_BERRY_BUSH("red_berry_bush", "&cBerry &aBush", HeadsPlusConfigCustomHeads.starter + "YmNlZTQ3ODdhYjg2ODg0MTViZDIyMzEyNTRiOGZkOWVmYzQ4ODljNGMzZWJkY2M2N2ZlZGI4M2I4YzQzOGMxIn19fQ", "plants", 1.0),
    CHORUS_PLANT("chorus_plant", "&5Chorus Plant", HeadsPlusConfigCustomHeads.starter + "YzQwZjFkYjk3MTRmYTE0M2IyY2Q0YWI0YjFhMTM0ZGJmMmZlYzVjZTA0OTExYjIxZWVmZTc5MTEzNjFlYjkifX19", "plants", 1.0),
    CHORUS_FLOWER("chorus_flower", "&dChorus Flower", HeadsPlusConfigCustomHeads.starter + "OTJlYjMwYTBiZTNkN2M3ZTE2MmM3NmU3MmEzYzRjYzQ0MjIzNTY3MTYyYTk0MTc1MjU3MmFlNmNjZWI5NmM4NiJ9fX0", "plants", 1.0),
    WHITE_SHEEP("white_sheep", "&fSheep", HeadsPlusConfigCustomHeads.starter + "ZjMxZjljY2M2YjNlMzJlY2YxM2I4YTExYWMyOWNkMzNkMThjOTVmYzczZGI4YTY2YzVkNjU3Y2NiOGJlNzAifX19", "animals", 1.1),
    RED_SHEEP("red_sheep", "&cSheep", HeadsPlusConfigCustomHeads.starter + "ODM5YWY0NzdlYjYyNzgxNWY3MjNhNTY2MjU1NmVjOWRmY2JhYjVkNDk0ZDMzOGJkMjE0MjMyZjIzZTQ0NiJ9fX0", "animals", 1.1),
    ORANGE_SHEEP("orange_sheep", "&6Sheep", HeadsPlusConfigCustomHeads.starter + "ZjA5ODM5N2EyNzBiNGMzZDJiMWU1NzRiOGNmZDNjYzRlYTM0MDkwNjZjZWZlMzFlYTk5MzYzM2M5ZDU3NiJ9fX0", "animals", 1.1),
    YELLOW_SHEEP("yellow_sheep", "&eSheep", HeadsPlusConfigCustomHeads.starter + "MjZhNDExMmRmMWU0YmNlMmE1ZTI4NDE3ZjNhYWZmNzljZDY2ZTg4NWMzNzI0NTU0MTAyY2VmOGViOCJ9fX0", "animals", 1.1),
    LIME_SHEEP("lime_sheep", "&aSheep", HeadsPlusConfigCustomHeads.starter + "OTJhMjQ0OGY1OGE0OTEzMzI0MzRlODVjNDVkNzg2ZDg3NDM5N2U4MzBhM2E3ODk0ZTZkOTI2OTljNDJiMzAifX19", "animals", 1.1),
    GREEN_SHEEP("green_sheep", "&2Sheep", HeadsPlusConfigCustomHeads.starter + "NmRlNTVhMzk1YTIyNDY0NDViNDVmOWE2ZDY4ODcyMzQ0YmJlYTU0ZjM2MmQ1MjlmYzViMGI4NTdlYTU4MzI2YiJ9fX0", "animals", 1.1),
    LIGHT_BLUE_SHEEP("light_blue_sheep", "&bSheep", HeadsPlusConfigCustomHeads.starter + "OWE2MjRmNTk2NmJlZGQ2ZTY3ZjY1NGI1OWU5MjQ5YjJlY2YzMDdkOTAzMzM5YmMxOTk5MjM5NzdmNGM4YyJ9fX0", "animals", 1.1),
    CYAN_SHEEP("cyan_sheep", "&3Sheep", HeadsPlusConfigCustomHeads.starter + "NDZmNmM3ZTdmZDUxNGNlMGFjYzY4NTkzMjI5ZTQwZmNjNDM1MmI4NDE2NDZlNGYwZWJjY2NiMGNlMjNkMTYifX19", "animals", 1.1),
    BLUE_SHEEP("blue_sheep", "&9Sheep", HeadsPlusConfigCustomHeads.starter + "ZDllYzIyODE4ZDFmYmZjODE2N2ZiZTM2NzI4YjI4MjQwZTM0ZTE2NDY5YTI5MjlkMDNmZGY1MTFiZjJjYTEifX19", "animals", 1.1),
    PURPLE_SHEEP("purple_sheep", "&5Sheep", HeadsPlusConfigCustomHeads.starter + "YWU1Mjg2N2FmZWYzOGJiMTRhMjZkMTQyNmM4YzBmMTE2YWQzNDc2MWFjZDkyZTdhYWUyYzgxOWEwZDU1Yjg1In19fQ", "animals", 1.1),
    MAGENTA_SHEEP("magenta_sheep", "&dSheep", HeadsPlusConfigCustomHeads.starter + "MTgzNjU2NWM3ODk3ZDQ5YTcxYmMxODk4NmQxZWE2NTYxMzIxYTBiYmY3MTFkNDFhNTZjZTNiYjJjMjE3ZTdhIn19fQ", "animals", 1.1),
    PINK_SHEEP("pink_sheep", "&dSheep", HeadsPlusConfigCustomHeads.starter + "MmFjNzRhMmI5YjkxNDUyZTU2ZmExZGRhNWRiODEwNzc4NTZlNDlmMjdjNmUyZGUxZTg0MWU1Yzk1YTZmYzVhYiJ9fX0", "animals", 1.1),
    SILVER_SHEEP("silver_sheep", "&7Sheep", HeadsPlusConfigCustomHeads.starter + "Y2UxYWM2ODM5OTNiZTM1NTEyZTFiZTMxZDFmNGY5OGU1ODNlZGIxNjU4YTllMjExOTJjOWIyM2I1Y2NjZGMzIn19fQ", "animals", 1.1),
    GRAY_SHEEP("gray_sheep", "&7Sheep", HeadsPlusConfigCustomHeads.starter + "NDI4N2ViNTAxMzkxZjI3NTM4OWYxNjZlYzlmZWJlYTc1ZWM0YWU5NTFiODhiMzhjYWU4N2RmN2UyNGY0YyJ9fX0", "animals", 1.1),
    BLACK_SHEEP("black_sheep", "&7Sheep", HeadsPlusConfigCustomHeads.starter + "MzI2NTIwODNmMjhlZDFiNjFmOWI5NjVkZjFhYmYwMTBmMjM0NjgxYzIxNDM1OTUxYzY3ZDg4MzY0NzQ5ODIyIn19fQ", "animals", 1.1),
    BROWN_SHEEP("brown_sheep", "&6Sheep", HeadsPlusConfigCustomHeads.starter + "YTU1YWQ2ZTVkYjU2OTJkODdmNTE1MTFmNGUwOWIzOWZmOWNjYjNkZTdiNDgxOWE3Mzc4ZmNlODU1M2I4In19fQ", "animals", 1.1),
    RED_BLOCK("red_block", "&cRed", HeadsPlusConfigCustomHeads.starter + "NWZkZTNiZmNlMmQ4Y2I3MjRkZTg1NTZlNWVjMjFiN2YxNWY1ODQ2ODRhYjc4NTIxNGFkZDE2NGJlNzYyNGIifX19", "colors", 1.2),
    ORANGE_BLOCK("orange_block", "&6Orange", HeadsPlusConfigCustomHeads.starter + "MmM0ODg2ZWYzNjJiMmM4MjNhNmFhNjUyNDFjNWM3ZGU3MWM5NGQ4ZWM1ODIyYzUxZTk2OTc2NjQxZjUzZWEzNSJ9fX0", "colors", 1.2),
    YELLOW_BLOCK("yellow_block", "&eYellow", HeadsPlusConfigCustomHeads.starter + "YzY0MTY4MmY0MzYwNmM1YzlhZDI2YmM3ZWE4YTMwZWU0NzU0N2M5ZGZkM2M2Y2RhNDllMWMxYTI4MTZjZjBiYSJ9fX0", "colors", 1.2),
    LIME_BLOCK("lime_block", "&aLime", HeadsPlusConfigCustomHeads.starter + "ZDI3Y2E0NmY2YTliYjg5YTI0ZmNhZjRjYzBhY2Y1ZTgyODVhNjZkYjc1MjEzNzhlZDI5MDlhZTQ0OTY5N2YifX19", "colors", 1.2),
    GREEN_BLOCK("green_block", "&2Green", HeadsPlusConfigCustomHeads.starter + "OGU5YjI3ZmNjZDgwOTIxYmQyNjNjOTFkYzUxMWQwOWU5YTc0NjU1NWU2YzljYWQ1MmU4NTYyZWQwMTgyYTJmIn19fQ", "colors", 1.2),
    LIGHT_BLUE_BLOCK("light_blue_block", "&bLight Blue", HeadsPlusConfigCustomHeads.starter + "MDdjNzhmM2VlNzgzZmVlY2QyNjkyZWJhNTQ4NTFkYTVjNDMyMzA1NWViZDJmNjgzY2QzZTgzMDJmZWE3YyJ9fX0", "colors", 1.2),
    CYAN_BLOCK("cyan_block", "&3Cyan", HeadsPlusConfigCustomHeads.starter + "NGMzNzRhY2VhNzhlZmJlZmE3OThiZTFiMjdlOTcxNGMzNjQxMWUyMDJlZWNkMzdiOGNmY2ZkMjQ5YTg2MmUifX19", "colors", 1.2),
    BLUE_BLOCK("blue_block", "&9Blue", HeadsPlusConfigCustomHeads.starter + "NmE0NjA1MzAxMmM2OGYyODlhYmNmYjE3YWI4MDQyZDVhZmJhOTVkY2FhOTljOTljMWUwMzYwODg2ZDM1In19fQ", "colors", 1.2),
    PURPLE_BLOCK("purple_block", "&5Purple", HeadsPlusConfigCustomHeads.starter + "YTMyYWUyY2I4ZDJhZTYxNTE0MWQyYzY1ODkyZjM2NGZjYWRkZjczZmRlYzk5YmUxYWE2ODc0ODYzZWViNWMifX19", "colors", 1.2),
    MAGENTA_BLOCK("magenta_block", "&dMagenta", HeadsPlusConfigCustomHeads.starter + "M2VmMGM1NzczZGY1NjBjYzNmYzczYjU0YjVmMDhjZDY5ODU2NDE1YWI1NjlhMzdkNmQ0NGYyZjQyM2RmMjAifX19", "colors", 1.2),
    PINK_BLOCK("pink_block", "&dPink", HeadsPlusConfigCustomHeads.starter + "NzNiMGFmODNkMGM3MjhhZWVjYTQ3MGYwOGExZDc1ZjQxY2VlMjUzYTM1NzNiYTQxNTdjYTI0MzNlNmMzNiJ9fX0", "colors", 1.2),
    WHITE_BLOCK("white_block", "&fWhite", HeadsPlusConfigCustomHeads.starter + "MzY2YTVjOTg5MjhmYTVkNGI1ZDViOGVmYjQ5MDE1NWI0ZGRhMzk1NmJjYWE5MzcxMTc3ODE0NTMyY2ZjIn19fQ", "colors", 1.2),
    LIGHT_GRAY_BLOCK("light_gray_block", "&7Light Gray", HeadsPlusConfigCustomHeads.starter + "MzhlMjk1NzY5OWJjOThhNGI1ZDYzNGFiNzE4NjdlZWIxODZiOTM0YmRiNjVkMmM0YjlkY2MyYjYxM2NmNSJ9fX0", "colors", 1.2),
    GRAY_BLOCK("gray_block", "&7Gray", HeadsPlusConfigCustomHeads.starter + "MmExN2U5NzAzN2NlMzUzZjg1ZjVjNjVkZjQzNWQyOTQ0OWE4OGRhNDQ0MmU0MzYxY2Y5OWFiYmUxZjg5MmZiIn19fQ", "colors", 1.2),
    BLACK("black_block", "&7Black", HeadsPlusConfigCustomHeads.starter + "OTY3YTJmMjE4YTZlNmUzOGYyYjU0NWY2YzE3NzMzZjRlZjliYmIyODhlNzU0MDI5NDljMDUyMTg5ZWUifX19", "colors", 1.2),
    BROWN("brown_block", "&6Brown", HeadsPlusConfigCustomHeads.starter + "ZjFmNWZmZmM2ZWYyODcyNGZiOWEwYzExMGQ5ZmE3ZDIzMGUzYWY1ZTkyMjk3ZTNkNjJkZjQ1MjcxYWUxZjQifX19", "colors", 1.2),
    RAINBOW("rainbow", "&4R&6a&ai&en&bb&3o&dw", HeadsPlusConfigCustomHeads.starter + "NTFlNDJiOGY1MGZlZDgyOGQ0Yjk4MWMyN2NhMTNkMDcxY2U4NjNmNjE1NDBiMjc2MzgyNjZmNzcyZDQxZCJ9fX0", "colors", 1.2),
    E_NEUTRAL("e_neutral", "&eNeutral Emote", HeadsPlusConfigCustomHeads.starter + "ODExNWRjYzE3YjJlMTVjZDQxODMxODg1ZDdkYmI4ZmYyZTljYWM0ZmVjNzA4MDM1OGZlNTVmOTNlZWExOWIifX19", "emotes", 1.3),
    E_SMILE("e_smile", "&eSmile Emote", HeadsPlusConfigCustomHeads.starter + "NTJlOTgxNjVkZWVmNGVkNjIxOTUzOTIxYzFlZjgxN2RjNjM4YWY3MWMxOTM0YTQyODdiNjlkN2EzMWY2YjgifX19", "emotes", 1.3),
    E_TONGUE("e_tongue", "&eTongue Out Emote", HeadsPlusConfigCustomHeads.starter + "N2ZmYWNjZjE3ODc5YjE3ODkxZmM1ZWY2NjQ3MmNjMDY2YTg1YmZhMzFiNmQ3ODZjMzJhZmVlNDc5NjA2OGQifX19", "emotes", 1.3),
    E_WINK("e_wink", "&eWink Emote", HeadsPlusConfigCustomHeads.starter + "ZjRlYTJkNmY5MzlmZWZlZmY1ZDEyMmU2M2RkMjZmYThhNDI3ZGY5MGIyOTI4YmMxZmE4OWE4MjUyYTdlIn19fQ", "emotes", 1.3),
    E_SURPRISED("e_surprised", "&eSurprised Emote", HeadsPlusConfigCustomHeads.starter + "YmMyYjliOWFlNjIyYmQ2OGFkZmY3MTgwZjgyMDZlYzQ0OTRhYmJmYTEzMGU5NGE1ODRlYzY5MmU4OTg0YWIyIn19fQ", "emotes", 1.3),
    E_DEAD("e_dead", "&eDead Emote", HeadsPlusConfigCustomHeads.starter + "YjM3MWU0ZTFjZjZhMWEzNmZkYWUyNzEzN2ZkOWI4NzQ4ZTYxNjkyOTk5MjVmOWFmMmJlMzAxZTU0Mjk4YzczIn19fQ", "emotes", 1.3),
    E_KISS("e_kiss", "&eKiss Emote", HeadsPlusConfigCustomHeads.starter + "NTQ1YmQxOGEyYWFmNDY5ZmFkNzJlNTJjZGU2Y2ZiMDJiZmJhYTViZmVkMmE4MTUxMjc3Zjc3OWViY2RjZWMxIn19fQ", "emotes", 1.3),
    E_CRYING("e_crying", "&eCrying Emote", HeadsPlusConfigCustomHeads.starter + "MWYxYjg3NWRlNDljNTg3ZTNiNDAyM2NlMjRkNDcyZmYyNzU4M2ExZjA1NGYzN2U3M2ExMTU0YjViNTQ5OCJ9fX0", "emotes", 1.3),
    E_DISAPPOINTED("e_disappointed", "&eDisappointed Emote", HeadsPlusConfigCustomHeads.starter + "ODNmZGNmMDQyZGFjYzczMmI2OTk1ODJjYWU3YzU5YTY1OWM4NmM1N2U0MzE0MmEyY2M4OWU0ZDllZjAzNyJ9fX0", "emotes", 1.3),
    E_SLEEPING("e_sleeping", "&eSleeping Emote", HeadsPlusConfigCustomHeads.starter + "OWM0YTQxNTU0MzQyYjJjYmZiZDg5NWU5ZWM3MDg5YWU4NjFmZWM4ZjUxNjkzODIyZWMxZWIzY2EzZjE4In19fQ", "emotes", 1.3),
    EMERALD_BLOCK("emerald_block", "&aEmerald Block", HeadsPlusConfigCustomHeads.starter + "YWM5MDZkNjg4ZTY1ODAyNTY5ZDk3MDViNTc5YmNlNTZlZGM4NmVhNWMzNmJkZDZkNmZjMzU1MTZhNzdkNCJ9fX0", "blocks", 1.6),
    DIAMOND_BLOCK("diamond_block", "&bDiamond Block", HeadsPlusConfigCustomHeads.starter + "OTYzMTU5N2RjZTRlNDA1MWU4ZDVhNTQzNjQxOTY2YWI1NGZiZjI1YTBlZDYwNDdmMTFlNjE0MGQ4OGJmNDhmIn19fQ", "blocks", 1.6),
    GOLD_BLOCK("gold_block", "&eGold Block", HeadsPlusConfigCustomHeads.starter + "NTRiZjg5M2ZjNmRlZmFkMjE4Zjc4MzZlZmVmYmU2MzZmMWMyY2MxYmI2NTBjODJmY2NkOTlmMmMxZWU2In19fQ", "blocks", 1.6),
    IRON_BLOCK("iron_block", "&fIron Block", HeadsPlusConfigCustomHeads.starter + "MTI2Yjc3MjMyOWNmMzJmODY0M2M0OTI4NjI2YjZhMzI1MjMzZmY2MWFhOWM3NzI1ODczYTRiZDY2ZGIzZDY5MiJ9fX0", "blocks", 1.6),
    REDSTONE_BLOCK("redstone_block", "&cRedstone Block", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmI3OGZhNWRlZmU3MmRlYmNkOWM3NmFiOWY0ZTExNDI1MDQ3OWJiOWI0NGY0Mjg4N2JiZjZmNzM4NjEyYiJ9fX0", "blocks", 1.6),
    COBBLESTONE("cobblestone", "&7Cobblestone", HeadsPlusConfigCustomHeads.starter + "ZGMxNzU0ODUxZTM2N2U4YmViYTJhNmQ4ZjdjMmZlZGU4N2FlNzkzYWM1NDZiMGYyOTlkNjczMjE1YjI5MyJ9fX0", "blocks", 1.6),
    GRASS_BLOCK("grass_block", "&aGrass Block", HeadsPlusConfigCustomHeads.starter + "Yzk1ZDM3OTkzZTU5NDA4MjY3ODQ3MmJmOWQ4NjgyMzQxM2MyNTBkNDMzMmEyYzdkOGM1MmRlNDk3NmIzNjIifX19", "blocks", 1.6),
    SNOW_GRASS_BLOCK("snow_grass_block", "&fSnow Grass Block", HeadsPlusConfigCustomHeads.starter + "NDNjNTJlYWU3NDdjYWQ1YjRmZDE5YjFhMjNiMzlhMzM2YjYyZWQ0MjI3OTdhNjIyZDA0NWY0M2U1ZDM4In19fQ", "blocks", 1.6),
    WOOD_PLANKS("wood_planks", "&6Wooden Planks", HeadsPlusConfigCustomHeads.starter + "MTBmOTZkOWI3MjMwM2YzNzI3OWZhOWMyY2MyM2VlNmY4ZGI2ODIzNjg1YjYyNmI1NmVkNTNiNjc0YjZiMCJ9fX0", "blocks", 1.6),
    DIAMOND_ORE("diamond_ore", "&bDiamond Ore", HeadsPlusConfigCustomHeads.starter + "MTFlZDlhYmY1MWZlNGVhODRjZmNiMjcyOTdmMWJjNTRjZDM4MmVkZjg1ZTdiZDZlNzVlY2NhMmI4MDY2MTEifX19", "blocks", 1.6),
    GOLD_ORE("gold_ore", "&eGold Ore", HeadsPlusConfigCustomHeads.starter + "NzNiYzk2NWQ1NzljM2M2MDM5ZjBhMTdlYjdjMmU2ZmFmNTM4YzdhNWRlOGU2MGVjN2E3MTkzNjBkMGE4NTdhOSJ9fX0", "blocks", 1.6),
    REDSTONE_ORE("redstone_ore", "&cRedstone Ore", HeadsPlusConfigCustomHeads.starter + "NTY5YTFmMTE0MTUxYjQ1MjEzNzNmMzRiYzE0YzI5NjNhNTAxMWNkYzI1YTY1NTRjNDhjNzA4Y2Q5NmViZmMifX19", "blocks", 1.6),
    COAL_BLOCK("coal_block", "&7Coal Block", HeadsPlusConfigCustomHeads.starter + "ZjZjNWVjYWM5NDJjNzdiOTVhYjQ2MjBkZjViODVlMzgwNjRjOTc0ZjljNWM1NzZiODQzNjIyODA2YTQ1NTcifX19", "blocks", 1.6),
    COAL_ORE("coal_ore", "&7Coal Ore", HeadsPlusConfigCustomHeads.starter + "NzYxYzU3OTc0ZjEwMmQzZGViM2M1M2Q0MmZkZTkwOWU5YjM5Y2NiYzdmNzc2ZTI3NzU3NWEwMmQ1MWExOTk5ZSJ9fX0", "blocks", 1.6),
    IRON_ORE("iron_ore", "&fIron ore", HeadsPlusConfigCustomHeads.starter + "MTAxODQzZWM0M2YwODhjOTYzZmZjM2UyZjcxYzY2ZTMxNTU5NDNiMTc3YTFhMzU5ODJiMTIwZjZmNjQ4MjJiYyJ9fX0", "blocks", 1.6),
    EMERALD_ORE("emerald_ore", "&aEmerald Ore", HeadsPlusConfigCustomHeads.starter + "NDA1Mzg1MTUyN2M0YzllZjMwYTYxZmIwNjdlYmNlOTU3YzcyNmUxNjg3ZjhiNTMwZmI0YTZiZWViYTQzOGJkIn19fQ", "blocks", 1.6),
    END_STONE("end_stone", "&eEnd Stone", HeadsPlusConfigCustomHeads.starter + "MTlmMjFmNWQ4ODMzMTZmZDY1YTkzNjZmMzJhMzMwMTMxODJlMzM4MWRlYzIxYzE3Yzc4MzU1ZDliZjRmMCJ9fX0", "blocks", 1.6),
    OAK_LOG("oak_log", "&6Oak Log", HeadsPlusConfigCustomHeads.starter + "NTRhYWRhNGQ5ZmNlZGE5MDE4NjkxOGQ2Y2EzNWI5YTBlYWQ4ZTRiMTRjOWQ5NDI3MTU3ZWU5YjkzMzlkN2IxIn19fQ", "blocks", 1.6),
    DIAMOND_BLOCK_2("diamond_block_2", "&bDiamond Block", HeadsPlusConfigCustomHeads.starter + "M2E0MzgxYTVhYjRhY2M2ZGU4ZDRlZWU3NjllYmE2YmFkYjJmMmI0ZTkzNDJhY2FlMjc1MDI5NWU2MDYwNGE1NyJ9fX0", "blocks", 1.7),
    EMERALD_BLOCK_2("emerald_block_2", "&aEmerald Block", HeadsPlusConfigCustomHeads.starter + "YjcyYzA1ZGQ3NjI4OGY0MzI4YTI0MzkxYmY0NzI1ZmQyMjYwNTkyZGIzY2Y5YjJiYzIwMzJkZDA1OTZjZjQ0MCJ9fX0", "blocks", 1.7),
    GOLD_BLOCK_2("gold_block_2", "&eGold Block", HeadsPlusConfigCustomHeads.starter + "YTU2NGU1NTM4MGQzOTkwMDJlMDFjZjBiMTI3NzRjZGE2YTdhMjZkODZiNTliZjg2MjkyODRlZjFhMzg3ZDRkMCJ9fX0", "blocks", 1.7),
    RED_MUSHROOM("red_mushroom", "&cRed Mushroom Block", HeadsPlusConfigCustomHeads.starter + "ODJlNjQyYmE2N2IwYmFkNWY3YWU5NTlhMjQ3YzlhZDFlYzRhOGM2MjQxNGJkZTU2YTgxMDY0Y2Q4YWY2OTE4YSJ9fX0", "blocks", 1.7),
    MISSING_TEXTURE("missing_texture", "&dMissing Texture", HeadsPlusConfigCustomHeads.starter + "YmNjMTEzZGNjZTE1ZmE0NTRjODQ1ZTk5MDk2MmY1ZjE2YTJhOTZmOTk2NTkwYzE2ZTVlMjQ0M2U0ZjgwMTVjNCJ9fX0", "blocks", 1.7),
    BRAIN_CORAL("brain_coral", "&dBrain Coral", HeadsPlusConfigCustomHeads.starter + "OTU3ZGQ0M2U4ZjFjZDEzNzI2YzBmOTlhYzQwNDcxNTA0N2QxMmViNDJhMjhmZmM2YWU5YmZiM2I3MGQ3NjQwYSJ9fX0", "blocks", 1.7),
    BUBBLE_CORAL("bubble_coral", "&dBubble Coral", HeadsPlusConfigCustomHeads.starter + "MTNmMTgwNWVkY2QzMmI5N2FiMmYxOWEwM2JhYWIxZjhkNGRjNGRiOGVjN2EwMDRiMTRlYjY2NmQwOWZiODdmMiJ9fX0", "blocks", 1.7),
    FIRE_CORAL("fire_coral", "&cFire Coral", HeadsPlusConfigCustomHeads.starter + "OWZlOGRlZDNjNzRlYWNkNzg0MTJhOTAzYjkwNGY1NTc3ODUwZDFlMjBkMzQ4NzhmZDc3NTk3YWQxNjMzYmY3NCJ9fX0", "blocks", 1.7),
    HORN_CORAL("horn_coral", "&eHorn Coral", HeadsPlusConfigCustomHeads.starter + "MzQ5MWI2ZTZhZTk0NTFjNDdlMDliZjFmZjIzZDUwZmZmODdiYTU5MjdhNTFmNDZmZmVkZjkyNmM1Y2JkZTc3ZiJ9fX0", "blocks", 1.7),
    TUBE_CORAL("tube_coral", "&9Tube Coral", HeadsPlusConfigCustomHeads.starter + "MzlmYzNjZjU1MDhkNDBjMTQ2OTlkNWJmN2YyNTI3NTllMTk1NmFmOWE2NmQxNWE2YzM4NTQzNzhjNjFmNmQ5YSJ9fX0", "blocks", 1.7),
    OAK_PLANKS("oak_planks", "&6Oak Planks", HeadsPlusConfigCustomHeads.starter + "MWIwZTExMzcwNGZjMjdjODhmOWU1MWFlODJlN2IwNWY3MDExYzQxMGYyMWUxOTEyMDViZWYyNTVhYTBkNmYzMSJ9fX0", "blocks", 1.8),
    BIRCH_PLANKS("birch_planks", "&eBirch Planks", HeadsPlusConfigCustomHeads.starter + "MWMzMmYxMGUwOTY1MGI2Zjk4NWFjZTk5MDYzNjA5N2JhOWE4NzZmNDljNWQ2MjZmMjkyYzNiMDhlYmY4MmMyMyJ9fX0", "blocks", 1.8),
    SPRUCE_PLANKS("spruce_planks", "&6Spruce Planks", HeadsPlusConfigCustomHeads.starter + "MTg2M2Y5MmI2ZDY2MzA1MjJhMTgwZWM0MjkxODY5YzFlNzAwZTUyNmM4NTRiZWUwNzM1NTcwOWVmM2I3NTk2YiJ9fX0", "blocks", 1.8),
    JUNGLE_PLANKS("jungle_planks", "&cJungle Planks", HeadsPlusConfigCustomHeads.starter + "NThiYzNlN2FkYTM3NDE4ZWM1YzYwNzlkMTJjMThhZGViNjQ4ZGM0NWRlMzYwMWNjYWE1YmYyMDVjOTAxNTk2YSJ9fX0", "blocks", 1.8),
    ACACIA_PLANKS("acacia_planks", "&cAcacia Planks", HeadsPlusConfigCustomHeads.starter + "MjZmYjc4NGRmZjFhNzYxNjNiNGE3MTc2ZjBiZDY2MjMwZWE5MDZiODJmODVlNDA5NGY0MTM0YTUwYzU5OTI4MSJ9fX0", "blocks", 1.8),
    DARK_OAK_PLANKS("dark_oak_planks", "&7Dark Oak Planks", HeadsPlusConfigCustomHeads.starter + "MjZmYjc4NGRmZjFhNzYxNjNiNGE3MTc2ZjBiZDY2MjMwZWE5MDZiODJmODVlNDA5NGY0MTM0YTUwYzU5OTI4MSJ9fX0", "blocks", 1.8),
    BONE_BLOCK("bone_block", "&fBone Block", HeadsPlusConfigCustomHeads.starter + "YjQzMGFiNTQ1YjE0MjgyN2I5MzVmYzdlMzBmZDFhMTczZmE5MWI5M2NhYmJhNDVmODVmMjJhZWVkMGFlZmFjNyJ9fX0", "blocks", 1.8),
    SNOWBALL("snowball", "&fSnowball", HeadsPlusConfigCustomHeads.starter + "MWRmZDc3MjRjNjlhMDI0ZGNmYzYwYjE2ZTAwMzM0YWI1NzM4ZjRhOTJiYWZiOGZiYzc2Y2YxNTMyMmVhMDI5MyJ9fX0", "blocks", 1.8),
    SNOWMAN("snowman", "&fSnowman", HeadsPlusConfigCustomHeads.starter + "NWY4NDZhZmM4OWU2Y2FiYTA1Y2Q2YzJjZTlkNTgzOTcyMDgwNTZlNmVlODI1OTM3ODc5ZTVkNmRiMTEyMWYifX19", "decoration", 2.2),
    BAT("bat", "&7Bat", HeadsPlusConfigCustomHeads.starter + "OWU5OWRlZWY5MTlkYjY2YWMyYmQyOGQ2MzAyNzU2Y2NkNTdjN2Y4YjEyYjlkY2E4ZjQxYzNlMGEwNGFjMWNjIn19fQ", "animals", 2.6),
    PERSIAN_CAT("persian_cat", "&ePersian Cat", HeadsPlusConfigCustomHeads.starter + "ZmY0MGM3NDYyNjBlZjkxYzk2YjI3MTU5Nzk1ZTg3MTkxYWU3Y2UzZDVmNzY3YmY4Yzc0ZmFhZDk2ODlhZjI1ZCJ9fX0", "animals", 2.6),
    BRITISH_SHORTHAIR_CAT("british_shorthair_cat", "&7British Shorthair", HeadsPlusConfigCustomHeads.starter + "NDcwMWY2NTU2ZjNjZjUyZjBhMzdmNGNhZTY2ODMxOWMxNTk3MTA4Y2JkZmI4MThjZjRiNDljMDNkZWJjZTgzZCJ9fX0", "animals", 2.6),
    JELLIE_CAT("jellie_cat", "&fJellie", HeadsPlusConfigCustomHeads.starter + "YTBkYjQxMzc2Y2E1N2RmMTBmY2IxNTM5ZTg2NjU0ZWVjZmQzNmQzZmU3NWU4MTc2ODg1ZTkzMTg1ZGYyODBhNSJ9fX0", "animals", 2.6),
    ALL_BLACK_CAT("all_black_cat", "&7Black Cat", HeadsPlusConfigCustomHeads.starter + "MjJjMWU4MWZmMDNlODJhM2U3MWUwY2Q1ZmJlYzYwN2UxMTM2MTA4OWFhNDdmMjkwZDQ2YzhhMmMwNzQ2MGQ5MiJ9fX0", "animals", 2.6),
    WHITE_CAT("white_cat", "&fWhite Cat", HeadsPlusConfigCustomHeads.starter + "ZTZlN2M1NzRiZTk3NzdjY2VlMWE5NzYwMWNlY2M1YmVkZDVlYTZkNjY3NjViNjQyNGQ2YjJlYmJmZTY2MjViMSJ9fX0", "animals", 2.6),
    SIAMESE_CAT("siamese_cat", "&fSiamese Cat", HeadsPlusConfigCustomHeads.starter + "Y2E3ZTFjYzZhYzZmYmUyOWIyYWE2YzZmYmJlYzViZDc4NWIxMmRmM2RjNjU5MDQxYzA0NjRiODMyN2FkOTMzIn19fQ", "animals", 2.6),
    BLACK_CAT("black_cat", "&7Tuxedo Cat", HeadsPlusConfigCustomHeads.starter + "ZDBkYmE5NDJjMDZiNzdhMjgyOGUzZjY2YTFmYWVjNWU4NjQzZTllYTYxYTgxYTQ1MjMyNzk3MzllZDgyZCJ9fX0", "animals", 2.6),
    RAGDOLL_CAT("ragdoll_cat", "&eRagdoll Cat", HeadsPlusConfigCustomHeads.starter + "ZGM3YTQ1ZDI1ODg5ZTNmZGY3Nzk3Y2IyNThlMjZkNGU5NGY1YmMxM2VlZjAwNzk1ZGFmZWYyZTgzZTBhYjUxMSJ9fX0", "animals", 2.6),
    RED_CAT("red_cat", "&6Red Cat", HeadsPlusConfigCustomHeads.starter + "OGViMmU0ZGIzYmNmYjA1MDNmMWZmZmIzMzk4ODhlNWQ0MzIzOThiMjc2OTljNWExYTFjZDgwNzljOGQ5N2QifX19", "animals", 2.6),
    TABBY_CAT("tabby_cat", "&eTabby Cat", HeadsPlusConfigCustomHeads.starter + "ZGUyOGQzMGRiM2Y4YzNmZTUwY2E0ZjI2ZjMwNzVlMzZmMDAzYWU4MDI4MTM1YThjZDY5MmYyNGM5YTk4YWUxYiJ9fX0", "animals", 2.6),
    CALICO_CAT("calico_cat", "&6Calico Cat", HeadsPlusConfigCustomHeads.starter + "NWY4NzIzODM2MjE0MTg3ZDY2ODQ1OTY1ZWNhNGM0NzY0NmFhMzQ5MzVhNjcyYWExYjk3YTIwNWQ2NWQxMTMifX19", "animals", 2.6),
    COD("cod", "&3Cod", HeadsPlusConfigCustomHeads.starter + "Nzg5MmQ3ZGQ2YWFkZjM1Zjg2ZGEyN2ZiNjNkYTRlZGRhMjExZGY5NmQyODI5ZjY5MTQ2MmE0ZmIxY2FiMCJ9fX0", "animals", 2.6),
    TROPICALFISH("tropicalfish", "&6Tropical Fish", HeadsPlusConfigCustomHeads.starter + "MTI1MTBiMzAxYjA4ODYzOGVjNWM4NzQ3ZTJkNzU0NDE4Y2I3NDdhNWNlNzAyMmM5YzcxMmVjYmRjNWY2ZjA2NSJ9fX0", "animals", 2.6),
    DOLPHIN("dolphin", "&bDolphin", HeadsPlusConfigCustomHeads.starter + "OGU5Njg4Yjk1MGQ4ODBiNTViN2FhMmNmY2Q3NmU1YTBmYTk0YWFjNmQxNmY3OGU4MzNmNzQ0M2VhMjlmZWQzIn19fQ", "animals", 2.6),
    DONKEY("donkey", "&7Donkey", HeadsPlusConfigCustomHeads.starter + "MjE0NGJkYWQ2YmMxOGEzNzE2YjE5NmRjNGE0YmQ2OTUyNjVlY2NhYWRkMGQ5NDViZWI5NzY0NDNmODI2OTNiIn19fQ", "animals", 2.6),
    DROWNED("drowned", "&bDrowned", HeadsPlusConfigCustomHeads.starter + "Yzg0ZGY3OWM0OTEwNGIxOThjZGFkNmQ5OWZkMGQwYmNmMTUzMWM5MmQ0YWI2MjY5ZTQwYjdkM2NiYmI4ZTk4YyJ9fX0", "mobs", 2.6),
    ELDERGUARDIAN("elderguardian", "&eElder Guardian", HeadsPlusConfigCustomHeads.starter + "MWM3OTc0ODJhMTRiZmNiODc3MjU3Y2IyY2ZmMWI2ZTZhOGI4NDEzMzM2ZmZiNGMyOWE2MTM5Mjc4YjQzNmIifX19", "mobs", 2.6),
    ENDERMITE("endermite", "&5Endermite", HeadsPlusConfigCustomHeads.starter + "NWJjN2I5ZDM2ZmI5MmI2YmYyOTJiZTczZDMyYzZjNWIwZWNjMjViNDQzMjNhNTQxZmFlMWYxZTY3ZTM5M2EzZSJ9fX0", "mobs", 2.6),
    EVOKER("evoker", "&7Evoker", HeadsPlusConfigCustomHeads.starter + "NjMwY2U3NzVlZGI2NWRiOGMyNzQxYmRmYWU4NGYzYzBkMDI4NWFiYTkzYWZhZGM3NDkwMGQ1NWRmZDk1MDRhNSJ9fX0", "mobs", 2.6),
    FOX("fox", "&6Fox", HeadsPlusConfigCustomHeads.starter + "MjRhMDM0NzQzNjQzNGViMTNkNTM3YjllYjZiNDViNmVmNGM1YTc4Zjg2ZTkxODYzZWY2MWQyYjhhNTNiODIifX19", "animals", 2.6),
    WHITE_HORSE("white_horse", "&fWhite Horse", HeadsPlusConfigCustomHeads.starter + "NjBhMmRiMmYxZWI5M2U1OTc4ZDJkYzkxYTc0ZGY0M2Q3Yjc1ZDllYzBlNjk0ZmQ3ZjJhNjUyZmJkMTUifX19", "animals", 2.6),
    CREAMY_HORSE("creamy_horse", "&eBuckskin Horse", HeadsPlusConfigCustomHeads.starter + "NjI4ZDFhYjRiZTFlMjhiN2I0NjFmZGVhNDYzODFhYzM2M2E3ZTVjMzU5MWM5ZTVkMjY4M2ZiZTFlYzlmY2QzIn19fQ", "animals", 2.6),
    CHESTNUT_HORSE("chestnut_horse", "&6Chestnut Horse", HeadsPlusConfigCustomHeads.starter + "YjY2YjJiMzJkMzE1MzljNzM4M2Q5MjNiYWU0ZmFhZjY1ZGE2NzE1Y2Q1MjZjMzVkMmU0ZTY4MjVkYTExZmIifX19", "animals", 2.6),
    BROWN_HORSE("brown_horse", "&6Brown Horse", HeadsPlusConfigCustomHeads.starter + "YmVkZjczZWExMmNlNmJkOTBhNGFlOWE4ZDE1MDk2NzQ5Y2ZlOTE4MjMwZGM4MjliMjU4MWQyMjNiMWEyYTgifX19", "animals", 2.6),
    DARK_BROWN_HORSE("dark_brown_horse", "&6Dark Brown Horse", HeadsPlusConfigCustomHeads.starter + "MjY2MWYyM2ZiNzY2MjRmZmJhYmJkYTMxY2E0YTM4YjQwNGZlNjNlZjM3ZDRiYTRlNGM1NDQxYTIxZTNhNiJ9fX0", "animals", 2.6),
    GRAY_HORSE("gray_horse", "&7Gray Horse", HeadsPlusConfigCustomHeads.starter + "ZDY2NzZjNGQ2ZjBmNWVkNjA2YTM1NmYzY2M1YTI5ZDE0YWFmZTY1NzIxYmExYTFhOTVjNWFjNGM1ZTIzOWU1In19fQ", "animals", 2.6),
    BLACK_HORSE("black_horse", "&7Black Horse", HeadsPlusConfigCustomHeads.starter + "NjRiN2ZjNWY3YTlkZGZkZDFhYTc5MzE3NDEwZmMxOTI5ZjkxYmRkZjk4NTg1OTM4YTJhNTYxOTlhNjMzY2MifX19", "animals", 2.6),
    HUSK("husk", "&eHusk", HeadsPlusConfigCustomHeads.starter + "ZDY3NGM2M2M4ZGI1ZjRjYTYyOGQ2OWEzYjFmOGEzNmUyOWQ4ZmQ3NzVlMWE2YmRiNmNhYmI0YmU0ZGIxMjEifX19", "mobs", 2.6),
    WHITE_LLAMA("white_llama", "&fWhite Llama", HeadsPlusConfigCustomHeads.starter + "ODNkOWI1OTE1OTEyZmZjMmI4NTc2MWQ2YWRjYjQyOGE4MTJmOWI4M2ZmNjM0ZTMzMTE2MmNlNDZjOTllOSJ9fX0", "animals", 2.6),
    GRAY_LLAMA("gray_llama", "&7LightGray Llama", HeadsPlusConfigCustomHeads.starter + "Y2YyNGU1NmZkOWZmZDcxMzNkYTZkMWYzZTJmNDU1OTUyYjFkYTQ2MjY4NmY3NTNjNTk3ZWU4MjI5OWEifX19", "animals", 2.6),
    BROWN_LLAMA("brown_llama", "&6Brown Llama", HeadsPlusConfigCustomHeads.starter + "YzJiMWVjZmY3N2ZmZTNiNTAzYzMwYTU0OGViMjNhMWEwOGZhMjZmZDY3Y2RmZjM4OTg1NWQ3NDkyMTM2OCJ9fX0", "animals", 2.6),
    CREAMY_LLAMA("creamy_llama", "&eCreamy Llama", HeadsPlusConfigCustomHeads.starter + "MmE1ZjEwZTZlNjIzMmYxODJmZTk2NmY1MDFmMWMzNzk5ZDQ1YWUxOTAzMWExZTQ5NDFiNWRlZTBmZWZmMDU5YiJ9fX0", "animals", 2.6),
    WHITE_TRADER_LLAMA("white_trader_llama", "&fWhite Trader Llama", HeadsPlusConfigCustomHeads.starter + "NzA4N2E1NTZkNGZmYTk1ZWNkMjg0NGYzNTBkYzQzZTI1NGU1ZDUzNWZhNTk2ZjU0MGQ3ZTc3ZmE2N2RmNDY5NiJ9fX0", "animals", 2.6),
    GRAY_TRADER_LLAMA("gray_trader_llama", "&7Light Gray Trader Llama", HeadsPlusConfigCustomHeads.starter + "YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0", "animals", 2.6),
    BROWN_TRADER_LLAMA("brown_trader_llama", "&6Brown Trader Llama", HeadsPlusConfigCustomHeads.starter + "YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0", "animals", 2.6),
    CREAMY_TRADER_LLAMA("creamy_trader_llama", "&eCreamy Trader Llama", HeadsPlusConfigCustomHeads.starter + "MmE1ZjEwZTZlNjIzMmYxODJmZTk2NmY1MDFmMWMzNzk5ZDQ1YWUxOTAzMWExZTQ5NDFiNWRlZTBmZWZmMDU5YiJ9fX0", "animals", 2.6),
    MAGMA_CUBE("magmacube", "&cMagma Cube", HeadsPlusConfigCustomHeads.starter + "Mzg5NTdkNTAyM2M5MzdjNGM0MWFhMjQxMmQ0MzQxMGJkYTIzY2Y3OWE5ZjZhYjM2Yjc2ZmVmMmQ3YzQyOSJ9fX0", "mobs", 2.6),
    MULE("mule", "&6Mule", HeadsPlusConfigCustomHeads.starter + "YTA0ODZhNzQyZTdkZGEwYmFlNjFjZTJmNTVmYTEzNTI3ZjFjM2IzMzRjNTdjMDM0YmI0Y2YxMzJmYjVmNWYifX19", "animals", 2.6),
    OCELOT("ocelot", "&eOcelot", HeadsPlusConfigCustomHeads.starter + "NTFmMDdlM2YyZTVmMjU2YmZhZGU2NjZhOGRlMWI1ZDMwMjUyYzk1ZTk4ZjhhOGVjYzZlM2M3YjdmNjcwOTUifX19", "animals", 2.6),
    RED_PARROT("red_parrot", "&cRed Parrot", HeadsPlusConfigCustomHeads.starter + "ZGNhMDk2ZWVhNTA2MzAxYmVhNmQ0YjE3ZWUxNjA1NjI1YTZmNTA4MmM3MWY3NGE2MzljYzk0MDQzOWY0NzE2NiJ9fX0", "animals", 2.6),
    GREEN_PARROT("green_parrot", "&aGreen Parrot", HeadsPlusConfigCustomHeads.starter + "YWI5YTM2YzU1ODlmM2EyZTU5YzFjYWE5YjNiODhmYWRhNzY3MzJiZGI0YTc5MjYzODhhOGMwODhiYmJjYiJ9fX0", "animals", 2.6),
    GRAY_PARROT("gray_parrot", "&7Gray Parrot", HeadsPlusConfigCustomHeads.starter + "M2Q2ZjRhMjFlMGQ2MmFmODI0Zjg3MDhhYzYzNDEwZjFhMDFiYmI0MWQ3ZjRhNzAyZDk0NjljNjExMzIyMiJ9fX0", "animals", 2.6),
    CYAN_PARROT("cyan_parrot", "&bCyan Parrot", HeadsPlusConfigCustomHeads.starter + "MmI5NGYyMzZjNGE2NDJlYjJiY2RjMzU4OWI5YzNjNGEwYjViZDVkZjljZDVkNjhmMzdmOGM4M2Y4ZTNmMSJ9fX0", "animals", 2.6),
    BLUE_PARROT("blue_parrot", "&9Blue Parrot", HeadsPlusConfigCustomHeads.starter + "YWNhNTgwYjA1MWM2M2JlMjlkYTU0NWE5YWE3ZmY3ZTEzNmRmNzdhODFjNjdkYzFlZTllNjE3MGMxNGZiMzEwIn19fQ", "animals", 2.6),
    PHANTOM("phantom", "&9Phantom", HeadsPlusConfigCustomHeads.starter + "N2U5NTE1M2VjMjMyODRiMjgzZjAwZDE5ZDI5NzU2ZjI0NDMxM2EwNjFiNzBhYzAzYjk3ZDIzNmVlNTdiZDk4MiJ9fX0", "mobs", 2.6),
    PIGZOMBIE("pigzombie", "&dZombie Pigman", HeadsPlusConfigCustomHeads.starter + "OTVmYjJkZjc1NGM5OGI3NDJkMzVlN2I4MWExZWVhYzlkMzdjNjlmYzhjZmVjZDNlOTFjNjc5ODM1MTZmIn19fQ", "mobs", 2.6),
    POLARBEAR("polarbear", "&fPolar Bear", HeadsPlusConfigCustomHeads.starter + "NDQyMTIzYWMxNWVmZmExYmE0NjQ2MjQ3Mjg3MWI4OGYxYjA5YzFkYjQ2NzYyMTM3NmUyZjcxNjU2ZDNmYmMifX19", "animals", 2.6),
    PUFFERFISH("pufferfish", "&6Pufferfish", HeadsPlusConfigCustomHeads.starter + "MTcxNTI4NzZiYzNhOTZkZDJhMjI5OTI0NWVkYjNiZWVmNjQ3YzhhNTZhYzg4NTNhNjg3YzNlN2I1ZDhiYiJ9fX0", "animals", 2.6),
    PILLAGER("pillager", "&7Pillager", HeadsPlusConfigCustomHeads.starter + "NGFlZTZiYjM3Y2JmYzkyYjBkODZkYjVhZGE0NzkwYzY0ZmY0NDY4ZDY4Yjg0OTQyZmRlMDQ0MDVlOGVmNTMzMyJ9fX0", "mobs", 2.6),
    RAVAGER("ravager", "&7Ravager", HeadsPlusConfigCustomHeads.starter + "MWNiOWYxMzlmOTQ4OWQ4NmU0MTBhMDZkOGNiYzY3MGM4MDI4MTM3NTA4ZTNlNGJlZjYxMmZlMzJlZGQ2MDE5MyJ9fX0", "mobs", 2.6),
    SHULKER("shulker", "&dShulker", HeadsPlusConfigCustomHeads.starter + "ZGQzN2Q0NzVjN2JiNjJkNTI5NjU3YWZjOGU3NjFjNjllOWIxMmNhMTRjMGE5MzlmZjY0MTZlYjI1ODkwNDc0YSJ9fX0", "mobs", 2.6),
    SILVERFISH("silverfish", "&7Silverfish", HeadsPlusConfigCustomHeads.starter + "ZGE5MWRhYjgzOTFhZjVmZGE1NGFjZDJjMGIxOGZiZDgxOWI4NjVlMWE4ZjFkNjIzODEzZmE3NjFlOTI0NTQwIn19fQ", "mobs", 2.6),
    SKELETONHORSE("skeletonhorse", "&fSkeleton Horse", HeadsPlusConfigCustomHeads.starter + "NDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ", "mobs", 2.6),
    STRAY("stray", "&bStray", HeadsPlusConfigCustomHeads.starter + "NzhkZGY3NmU1NTVkZDVjNGFhOGEwYTVmYzU4NDUyMGNkNjNkNDg5YzI1M2RlOTY5ZjdmMjJmODVhOWEyZDU2In19fQ", "mobs", 2.6),
    VEX("vex", "&bVex", HeadsPlusConfigCustomHeads.starter + "YzJlYzVhNTE2NjE3ZmYxNTczY2QyZjlkNWYzOTY5ZjU2ZDU1NzVjNGZmNGVmZWZhYmQyYTE4ZGM3YWI5OGNkIn19fQ", "mobs", 2.6),
    VINDICATOR("vindicator", "&7Vindicator", HeadsPlusConfigCustomHeads.starter + "NmRlYWVjMzQ0YWIwOTViNDhjZWFkNzUyN2Y3ZGVlNjFiMDYzZmY3OTFmNzZhOGZhNzY2NDJjODY3NmUyMTczIn19fQ", "mobs", 2.6),
    WANDERING_TRADER("wandering_trader", "&9Wandering Trader", HeadsPlusConfigCustomHeads.starter + "NWYxMzc5YTgyMjkwZDdhYmUxZWZhYWJiYzcwNzEwZmYyZWMwMmRkMzRhZGUzODZiYzAwYzkzMGM0NjFjZjkzMiJ9fX0", "mobs", 2.6),
    WITHER("wither", "&7Wither", HeadsPlusConfigCustomHeads.starter + "Y2RmNzRlMzIzZWQ0MTQzNjk2NWY1YzU3ZGRmMjgxNWQ1MzMyZmU5OTllNjhmYmI5ZDZjZjVjOGJkNDEzOWYifX19", "mobs", 2.6),
    WOLF("wolf", "&7Wolf", HeadsPlusConfigCustomHeads.starter + "NjlkMWQzMTEzZWM0M2FjMjk2MWRkNTlmMjgxNzVmYjQ3MTg4NzNjNmM0NDhkZmNhODcyMjMxN2Q2NyJ9fX0", "mobs", 2.6),
    ZOMBIEHORSE("zombiehorse", "&aZombie Horse", HeadsPlusConfigCustomHeads.starter + "ZDIyOTUwZjJkM2VmZGRiMThkZTg2ZjhmNTVhYzUxOGRjZTczZjEyYTZlMGY4NjM2ZDU1MWQ4ZWI0ODBjZWVjIn19fQ", "mobs", 2.6),
    ZOMBIEVILLAGER("zombievillager", "&aZombie Villager", HeadsPlusConfigCustomHeads.starter + "ZTVlMDhhODc3NmMxNzY0YzNmZTZhNmRkZDQxMmRmY2I4N2Y0MTMzMWRhZDQ3OWFjOTZjMjFkZjRiZjNhYzg5YyJ9fX0", "mobs", 2.6),
    GOLDEN_CHECK("golden_check", "&eGolden Check", HeadsPlusConfigCustomHeads.starter + "NjFmZTc0ZjY0YWJkMWE4MTQ3YzEzNzBmY2YzMTIyOTI4MDFiZjRjMzcxZjE1NjRkODkwNGRjMWI3YmU2NGRjOCJ9fX0", "alphabet", 2.7),
    RED_EXCLAMATION_MARK("red_exclamation_mark", "&cRed Exclamation Mark", HeadsPlusConfigCustomHeads.starter + "ZTdmOWM2ZmVmMmFkOTZiM2E1NDY1NjQyYmE5NTQ2NzFiZTFjNDU0M2UyZTI1ZTU2YWVmMGE0N2Q1ZjFmIn19fQ", "alphabet", 2.7),
    BEE_MC("bee_mc", "&6Bee (MC)", HeadsPlusConfigCustomHeads.starter + "NTlhYzE2ZjI5NmI0NjFkMDVlYTA3ODVkNDc3MDMzZTUyNzM1OGI0ZjMwYzI2NmFhMDJmMDIwMTU3ZmZjYTczNiJ9fX0", "animals", 2.9),
    BEE_POLLINATED("bee_pollinated", "&6Bee (Pollinated)", HeadsPlusConfigCustomHeads.starter + "YjcyN2QwYWIwM2Y1Y2QwMjJmODcwNWQzZjdmMTMzY2E0OTIwZWFlOGUxZTQ3YjUwNzQ0MzNhMTM3ZTY5MWU0ZSJ9fX0", "animals", 2.9),
    BEE_ANGRY("bee_angry", "&6Bee (Angry)", HeadsPlusConfigCustomHeads.starter + "ZTQwMDIyM2YxZmE1NDc0MWQ0MjFkN2U4MDQ2NDA5ZDVmM2UxNWM3ZjQzNjRiMWI3Mzk5NDAyMDhmM2I2ODZkNCJ9fX0", "animals", 2.9),
    BEE_POLLINATED_ANGRY("bee_pollinated_angry", "&6Bee (Angry, Pollinated)", HeadsPlusConfigCustomHeads.starter + "ZTZiNzRlMDUyYjc0Mjg4Nzk5YmE2ZDlmMzVjNWQwMjIxY2Y4YjA0MzMxNTQ3ZWMyZjY4ZDczNTk3YWUyYzliIn19fQ", "animals", 2.9),
    CHARGED_CREEPER("charged_creeper", "&aCreeper (Charged)", HeadsPlusConfigCustomHeads.starter + "ZjJjZWIzOWRkNGRlMjRhN2FkZmUyOTFhM2EwY2ZjN2NmNGY2NDVkZTU5YjYwM2ZjZmUwNmM2YjVhMDZlMjYifX19", "mobs", 2.9),
    FOX_MC("fox_mc", "&6Fox (MC)", HeadsPlusConfigCustomHeads.starter + "ZDg5NTRhNDJlNjllMDg4MWFlNmQyNGQ0MjgxNDU5YzE0NGEwZDVhOTY4YWVkMzVkNmQzZDczYTNjNjVkMjZhIn19fQ", "animals", 2.9),
    SNOW_FOX("snow_fox", "&fSnow Fox", HeadsPlusConfigCustomHeads.starter + "NDE0MzYzNzdlYjRjNGI0ZTM5ZmIwZTFlZDg4OTlmYjYxZWUxODE0YTkxNjliOGQwODcyOWVmMDFkYzg1ZDFiYSJ9fX0", "animals", 2.9),
    VILLAGER_PLAINS("villager_plains", "&6Villager (Plains)", HeadsPlusConfigCustomHeads.starter + "ZDE0YmZmMWEzOGM5MTU0ZTVlYzg0Y2U1Y2YwMGM1ODc2OGUwNjhlYjQyYjJkODlhNmJiZDI5Nzg3NTkwMTA2YiJ9fX0", "humans", 2.9),
    VILLAGER_JUNGLE("villager_jungle", "&aVillager (Jungle)", HeadsPlusConfigCustomHeads.starter + "NDRiMDYyYTlmODM5OWRjY2I2MjUxYTc0ZTYxODY0NzM0MmEzYzAyNDBjYTU2ZjM0NjE0ZDUyZjYwYTNmZWNlYyJ9fX0", "humans", 2.9),
    VILLAGER_SAVANNA("villager_savanna", "&6Villager (Savanna)", HeadsPlusConfigCustomHeads.starter + "NTIyNTY4MzU0ZjUzNWIwOTQwMzVjZWU4NjhhNGY3OTg1Nzg4YmQ1NzU1YjgwYzBkYzhkZmM0NDM5NjlmYWVhNyJ9fX0", "humans", 2.9),
    VILLAGER_DESERT("villager_desert", "&eVillager (Desert)", HeadsPlusConfigCustomHeads.starter + "Nzg3Y2I1MzJmODViMzNiM2IxNDEwMjBhYTA1MWMzNWRjOGU5Y2MwYWUxM2VhMjU4ZjFkZmU1ZTA0NDVmM2JjYyJ9fX0", "humans", 2.9),
    VILLAGER_SNOW("villager_snow", "&eVillager (Snow)", HeadsPlusConfigCustomHeads.starter + "MjBjNjQxZTNkMzc2NGVkMWMxZjE5MDdjNDMzNGUyYjEzMDNlMjE1MmIxM2QxZWIwYzYwNTc2M2Y5N2ZiMjU4YSJ9fX0", "humans", 2.9),
    VILLAGER_SWAMP("villager_swamp", "&aVillager (Swamp)", HeadsPlusConfigCustomHeads.starter + "NTFkZjFmZDBmOTkzN2M2MzFjNmVjMjZlNGI0ZWM2MWRkNmJhMWRmYjJiYTA3OGY0NjM3OWQ5OTNlZTg4ZDczNSJ9fX0", "humans", 2.9),
    VILLAGER_TAIGA("villager_taiga", "&aVillager (Taiga)", HeadsPlusConfigCustomHeads.starter + "MzdkMjE0N2FjNDdhMWM5NTg4NTU3ZjkyZjgzMTA5MjYyYTkzZWNmMzIxNzBhYThiNjIwNTZlMTYyOWY3OTBhMiJ9fX0", "humans", 2.9),
    RED_MOOSHROOM("red_mooshroom", "&cMooshroom", HeadsPlusConfigCustomHeads.starter + "MmI1Mjg0MWYyZmQ1ODllMGJjODRjYmFiZjllMWMyN2NiNzBjYWM5OGY4ZDZiM2RkMDY1ZTU1YTRkY2I3MGQ3NyJ9fX0", "animals", 2.9),
    BROWN_MOOSHROOM("brown_mooshroom", "&6Mooshroom", HeadsPlusConfigCustomHeads.starter + "YjZkNWZjNzAzMWFjYzk1YmVlYjUyODc1ZjE1NDA4ZTk3OWEwYTljMzkxYjZkYjdlY2VlN2U0MDAwNzJkZTVjNCJ9fX0", "animals", 2.9),
    BROWN_RABBIT("brown_rabbit", "&6Brown Rabbit", HeadsPlusConfigCustomHeads.starter + "N2QxMTY5YjI2OTRhNmFiYTgyNjM2MDk5MjM2NWJjZGE1YTEwYzg5YTNhYTJiNDhjNDM4NTMxZGQ4Njg1YzNhNyJ9fX0", "animals", 2.9),
    WHITE_RABBIT("white_rabbit", "&fWhite Rabbit", HeadsPlusConfigCustomHeads.starter + "Mzc0ZDgyOTg3OTdlNzEyYmIxZjc1YWQ2ZmZhNzczNGFjNDIzN2VhNjliZTFkYjkyZjBlNDExMTVhMmMxNzBjZiJ9fX0", "animals", 2.9),
    BLACK_RABBIT("black_rabbit", "&7Black Rabbit", HeadsPlusConfigCustomHeads.starter + "NzJjNTgxMTZhMTQ3ZDFhOWEyNjI2OTIyNGE4YmUxODRmZThlNWYzZjNkZjliNjE3NTEzNjlhZDg3MzgyZWM5In19fQ", "animals", 2.9),
    BLACK_AND_WHITE_RABBIT("black_and_white_rabbit", "&fBlack and White Rabbit", HeadsPlusConfigCustomHeads.starter + "Y2I4Y2ZmNGIxNWI4Y2EzN2UyNTc1MGYzNDU3MThmMjg5Y2IyMmM1YjNhZDIyNjI3YTcxMjIzZmFjY2MifX19", "animals", 2.9),
    GOLD_RABBIT("gold_rabbit", "&eGolden Rabbit", HeadsPlusConfigCustomHeads.starter + "Yzk3N2EzMjY2YmYzYjllYWYxN2U1YTAyZWE1ZmJiNDY4MDExNTk4NjNkZDI4OGI5M2U2YzEyYzljYiJ9fX0", "animals", 2.9),
    SALT_AND_PEPPER_RABBIT("salt_and_pepper_rabbit", "&6Salt and Pepper Rabbit", HeadsPlusConfigCustomHeads.starter + "ZmZlY2M2YjVlNmVhNWNlZDc0YzQ2ZTc2MjdiZTNmMDgyNjMyN2ZiYTI2Mzg2YzZjYzc4NjMzNzJlOWJjIn19fQ", "animals", 2.9),
    THE_KILLER_BUNNY_RABBIT("the_killer_bunny_rabbit", "&cKiller Bunny", HeadsPlusConfigCustomHeads.starter + "MWY1OTg1MWRlOTNmNGM2NTQ3ZjgwOWNhM2FlZDE4OWU5NGJiZjRmODg4ZjFmNzUyMDhlOTRjMzczMzg1MmExIn19fQ", "animals", 2.9),
    ZOMBIE_VILLAGER_PLAINS("zombie_villager_plains", "&aZombie Villager (Plains)", HeadsPlusConfigCustomHeads.starter + "OGM3NTA1ZjIyNGQ1MTY0YTExN2Q4YzY5ZjAxNWY5OWVmZjQzNDQ3MWM4YTJkZjkwNzA5NmM0MjQyYzM1MjRlOCJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_TAIGA("zombie_villager_taiga", "&aZombie Villager (Taiga)", HeadsPlusConfigCustomHeads.starter + "Mjc5ODYyMTI0ZmNmOTVhZWNlNzA4NjI0ZDQwYTRmZTQ2NTgzNTExMTNlNDM2NTI0ZWI1ZjIwZjhmZTVlNjZiNiJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_SWAMP("zombie_villager_swamp", "&aZombie Villager (Swamp)", HeadsPlusConfigCustomHeads.starter + "MjJjY2EyZDlmMGFlZjQyY2MzMDg2NDE1ZTE0MTk1NjBmMzQzMzRiMTY3YmViZmVmZWNjNDM0OTJjYjE0MTc4OSJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_SAVANNA("zombie_villager_savanna", "&aZombie Villager (Savanna)", HeadsPlusConfigCustomHeads.starter + "YWIyNGVjMzk5ODI1MGY5NTA4MzYxMDM5MTgyMjY2Njg3MTAzYjg5NGVjOGI5NDg4M2ZlYWNkM2MzNTFkYjUwNiJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_JUNGLE("zombie_villager_jungle", "&aZombie Villager (Jungle)", HeadsPlusConfigCustomHeads.starter + "NjQ5YTQ2Mjc1ZGVjMGMyNDdkZjk4NmRmYjRiMzUxZDI4OWYwMjQyYjVmY2Q2MjBkYWFlMTEzNzI1NzIwYzdjOSJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_DESERT("zombie_villager_desert", "&aZombie Villager (Desert)", HeadsPlusConfigCustomHeads.starter + "ODVhYmRlN2JhOTllNWNmZGFhZWFjNTE0YzZhYTFkNGI0YWVhMGQxZTNjNTY5MWQ1NjA4MjhkNjYxZjQzM2RkMiJ9fX0", "humans", 2.9),
    ZOMBIE_VILLAGER_SNOW("zombie_villager_snow", "&aZombie Villager (Snow)", HeadsPlusConfigCustomHeads.starter + "ZWYxMmI3YjUzMDAxZWY4NTE3MTlmZGY4YzA4OGRlMDNiMTFkNGFlNDNmNmZmNTNhYzVhMjY3ZDI0ZGYxZGM2MCJ9fX0", "humans", 2.9),
    PANDA_NORMAL("panda_normal", "&fPanda", HeadsPlusConfigCustomHeads.starter + "ZGNhMDk2ZWVhNTA2MzAxYmVhNmQ0YjE3ZWUxNjA1NjI1YTZmNTA4MmM3MWY3NGE2MzljYzk0MDQzOWY0NzE2NiJ9fX0", "animals", 2.9),
    PANDA_PLAYFUL("panda_playful", "&fPanda (Playful)", HeadsPlusConfigCustomHeads.starter + "YjY0NjNlNjRjZTI5NzY0ZGIzY2I0NjgwNmNlZTYwNmFmYzI0YmRmMGNlMTRiNjY2MGMyNzBhOTZjNzg3NDI2In19fQ", "animals", 2.9),
    PANDA_AGGRESSIVE("panda_aggressive", "&fPanda (Aggressive)", HeadsPlusConfigCustomHeads.starter + "ODNmZTFlNzgyYWU5NmEzMDMzNmEwM2VmNzQ2ODFjZTNhNjkwNWZjYzY3M2ZhNTZjMDQ2YWFlZTZhYTI4MzA3ZCJ9fX0", "animals", 2.9),
    PANDA_WORRIED("panda_worried", "&fPanda (Worried)", HeadsPlusConfigCustomHeads.starter + "YzhlOTIxYzU3ZTU0ZGQwNzMzN2ZmYmE2MjllNzJjYWYzODUwZDgzNmI3NjU2MmIxYmMzYmM1OTQ5ZjJkNDFkIn19fQ", "animals", 2.9),
    PANDA_BROWN("panda_brown", "&fPanda (Brown)", HeadsPlusConfigCustomHeads.starter + "YzVkMGQ0NWJmOTkyYjA3MmNmNWM1MTNlMDZiZWVmZThiZGM4MDljODE1MGYzZDE0Yjg4Mzc5NmE3Yjc0ZTQwNiJ9fX0", "animals", 2.9),
    PANDA_WEAK("panda_weak");

    final String name;
    final String dn;
    final String tex;
    final String sec;
    final Double v;

    HeadsXEnums(String name, String dn, String texture, String section, Double version ) {
        this.name = name;
        this.dn = "&8❰ " + dn + " &8❱";
        this.tex = texture;
        this.sec = section;
        this.v = version;
    }
}
